<template>
    <div id="mainWrapper">
        <div id="tools-bar">
            <span class="title">档案模板管理</span>
            
            <el-button type="info" class="close-btn" icon="el-icon-back" @click="backDeskClick"></el-button>
        </div>
        <div class="line"></div>
        <div id="mainContent">
            <div id="treeWrapper">
                <div style="position:fixed">
                    <el-button-group >
                        <el-button type="primary" @click="showAddTreeNodeDialog" icon="el-icon-plus">增加节点</el-button>
                        <el-button type="primary" @click="deleteTreeNode" icon="el-icon-delete">删除节点</el-button>
                        <el-button type="primary" icon="el-icon-sort" >结构复制</el-button>
                        
                    </el-button-group>
                    <ul id="templeteTree" class="ztree" style="margin-top:1px"></ul>
                </div>
                
                
            </div>
            <div id="workSpace" v-if="showMenu">
                <div class="tab-menu">
                    <div class="tab-menu-item" :class="{'tab-active':activeTabIndex == 0}" @click="activeTabIndex = 0">结构定义</div>
                    <div class="tab-menu-item" :class="{'tab-active':activeTabIndex == 1}" @click="activeTabIndex = 1">报表维护</div>
                    <!-- <div class="tab-menu-item" :class="{'tab-active':activeTabIndex == 2}" @click="activeTabIndex = 2">排序设置</div> -->
                    <div class="tab-menu-item" :class="{'tab-active':activeTabIndex == 3}" @click="activeTabIndex = 3" v-if="showMount">挂接规则</div>
                    
                </div>
                <div class="tab-content"  id="structDefineSpace" v-show="activeTabIndex == 0">
                    <el-button-group style="height:28px">
                        <el-button type="primary" icon="el-icon-plus" @click="structDefine.addColumnDialogVisible = true" >增加字段</el-button>
                        <el-button type="primary" icon="el-icon-edit" @click="structDefine.updateColumnDialogVisible = true">修改字段</el-button>
                        <el-button type="primary" icon="el-icon-delete" @click="deleteColumn">删除字段</el-button>
                    </el-button-group>
                    <v-table
                        style="width:100%;margin-top:5px"
                        :vertical-resize-offset="10"
                        :is-vertical-resize="true"
                        :column-width-drag="true"
                        odd-bg-color="#FCFCFC"
                        even-bg-color="	#FDF5E6"
                        :is-horizontal-resize="true"
                        :title-row-height="40"
                        :row-height="30"
                        title-bg-color="#87CEEB"
                        row-hover-color="#1E90FF"
                        row-click-color="#1E90FF"
                        :columns="structDefine.columns"
                        :table-data="structDefine.tableData"
                        :selectChange="selectChange"
                        :row-click="rowClick"
                    ></v-table>
                    <!-- <div style="height:50px"></div> -->
                </div>
                <div class="tab-content" id="reportDefineSpace"  v-show="activeTabIndex == 1">
                    报表模板
                </div>
                <div class="tab-content" id="sortDefineSpace"  v-show="activeTabIndex == 2">
                    <el-button-group style="height:28px">
                        <el-button type="primary" icon="el-icon-delete">取消</el-button>
                        <el-button type="primary" @click="commitSortRules" icon="el-icon-delete">保存</el-button>
                    </el-button-group>
                    <ul class="sort-container">
                        <li  v-for="(item,index) in sortDefine.data" :key="item.id">
                            <input type="checkbox" :checked="item.sortType != 0" name="" id="" @change="checkedChange(index)" style="height:30px">
                            <span class="column-name-container">{{item.columnName}}</span>
                            <span class="sort-level-container">{{item.sortLevel != 0 && item.sortType != 0?item.sortLevel:""}}</span> 
                            <select name="" id="" v-model="item.sortType" @change="changSortType(index)" :disabled="item.sortLevel == 0">
                                <option :selected="item.sortType == 0" value="0"></option>
                                <option :selected="item.sortType == 1" value="1">升序</option>
                                <option :selected="item.sortType == -1" value="-1">降序</option>
                            </select>
                        </li>
                    </ul>
                </div>
                <div class="tab-content" id="mountDefineSpace"  v-show="activeTabIndex == 3" v-if="showMount">
                    
                    <div class="mountContent">
                        <div class="mountLi">
                            
                            <ul class="mount-container">
                                <li>
                                    <input type="radio" name="checkboxName" id="" @change="mountDefine.mountAdd=-1"  value="">
                                    <input type="text" style="width:80px;text-align:center" v-model="mountDefine.mountVal">
                                </li>
                                <li  v-for="(item,index) in this.structDefine.tableData" :key="item.id">
                                    <input type="radio" name="checkboxName" id="" @change="mountDefine.mountAdd=index"  value="">
                                    <span >{{item.columnName}}</span>           
                                </li>
                            </ul>
                        </div>
                        <div class="mountAdd">
                            <el-button type="primary" @click="mountAddClick(mountDefine.mountAdd)">添加<i class="el-icon-d-arrow-right"></i></el-button>
                            
                        </div>
                        <div class='mountData'>
                            <h3>挂接规则:</h3>
                            <span style="margin-top:15px">{{this.mountDefine.mountData+'\.'+'pdf'}}</span>
                            
                        </div>
                        
                    </div>
                    <div style="margin-top:30px;text-align:center">
                        <el-button type="primary" @click="addMountData">提交</el-button>
                        <el-button type="primary" @click="unaddMountData">重置</el-button>
                    </div>
                       
                </div>
            </div>
        </div>
        <el-dialog  
            title="添加子节点"
            :visible.sync="addTreeNodeDialogVisible"
            width="40%"
            :before-close="handleClose">
            <el-input v-model="childeProps.nodeName" placeholder="请输入节点名称"></el-input>
            <h3>节点类型</h3><br/>
                <el-radio v-model="childeProps.nodeType" label="1">分类节点</el-radio>
                <el-radio  v-model="childeProps.nodeType" label="2">模板节点</el-radio>
            <h3 v-show="childeProps.nodeType == 2">模板类型</h3><br/>
            <el-checkbox-group v-show="childeProps.nodeType == 2" v-model="childeProps.templateType">
                <el-checkbox label="案卷级"></el-checkbox>
                <el-checkbox label="件盒级"></el-checkbox>
            </el-checkbox-group>
            <span slot="footer" class="dialog-footer">
                <el-button @click="addTreeNodeDialogVisible = false">取 消</el-button>
                <el-button type="primary" @click="addChildNode">确 定</el-button>
            </span>
        </el-dialog>
        
        <el-dialog  
            title="增加字段"
            :visible.sync="structDefine.addColumnDialogVisible"
            width="40%"
            :before-close="handleClose">
            <el-form ref="addColumnform"  label-width="80px">
                <el-form-item label="字段名称">
                    <el-input v-model="structDefine.columnPros.columnName" 
                            @change="structDefine.columnPros.abcName = getPY(structDefine.columnPros.columnName) "    
                    ></el-input>
                </el-form-item>
                <el-form-item label="字段代码">
                    <el-input v-model="structDefine.columnPros.abcName" :disabled="true"></el-input>
                </el-form-item>
                <el-form-item label="字段类型">
                    <el-select  placeholder="请选择字段类型" v-model="structDefine.columnPros.columnType">
                        <!-- <el-option v-for="item in structDefine.columnTypeOptions" :key="item.value" :label="item.label" :value="item.value"></el-option> -->
                        <el-option label="字符型" value="char"></el-option>
                        <el-option label="整型" value="int"></el-option>
                        <el-option label="浮点型" value="float"></el-option>
                        <el-option label="日期型" value="date"></el-option>
                    </el-select>
                </el-form-item>
                <el-form-item label="字段长度">
                    <el-input-number v-model="structDefine.columnPros.columnLength" :min="1" :max="500" label="字段长度"></el-input-number>
                </el-form-item>
                <el-form-item label="排序类型">
                    <el-select  placeholder="请选择排序类型" v-model="structDefine.columnPros.sortType">
                        <!-- <el-option v-for="item in structDefine.columnTypeOptions" :key="item.value" :label="item.label" :value="item.value"></el-option> -->
                        <el-option label="不参与排序" value="0"></el-option>
                        <el-option label="升序" value="1"></el-option>
                        <el-option label="降序" value="-1"></el-option>
                    </el-select>
                </el-form-item>
                <el-form-item label="优先级">
                    <el-input-number v-model="structDefine.columnPros.sortlevel" :min="1" :max="100" label="优先级"></el-input-number>
                </el-form-item>                
            </el-form>
            <span slot="footer" class="dialog-footer">
                <el-button @click="structDefine.addColumnDialogVisible = false">取 消</el-button>
                <el-button type="primary" @click="addColumn">确 定</el-button>
            </span>
        </el-dialog>
        <el-dialog  
            title="修改字段"
            :visible.sync="structDefine.updateColumnDialogVisible"
            width="40%"
            :before-close="handleClose">
            <el-form ref="addColumnform"  label-width="80px">
                <el-form-item label="字段名称">
                    <el-input v-model="structDefine.columnPros.columnName" @change="structDefine.columnPros.abcName = getPY(structDefine.columnPros.columnName) "></el-input>
                </el-form-item>
                <el-form-item label="字段代码">
                    <el-input v-model="structDefine.columnPros.abcName" :disabled="true"></el-input>
                </el-form-item>
                <el-form-item label="字段类型">
                    <el-select  placeholder="请选择字段类型" v-model="structDefine.columnPros.columnType">
                        <!-- <el-option v-for="item in structDefine.columnTypeOptions" :key="item.value" :label="item.label" :value="item.value"></el-option> -->
                        <el-option label="字符型" value="char"></el-option>
                        <el-option label="整型" value="int"></el-option>
                        <el-option label="浮点型" value="float"></el-option>
                        <el-option label="日期型" value="date"></el-option>
                    </el-select>
                </el-form-item>
                <el-form-item label="字段长度">
                    <el-input-number v-model="structDefine.columnPros.columnLength" :min="1" :max="500" label="字段长度"></el-input-number>
                </el-form-item>
                <el-form-item label="排序类型">
                    <el-select  placeholder="请选择排序类型" v-model="structDefine.columnPros.sortType">
                        <!-- <el-option v-for="item in structDefine.columnTypeOptions" :key="item.value" :label="item.label" :value="item.value"></el-option> -->
                        <el-option label="不参与排序" value="0"></el-option>
                        <el-option label="升序" value="1"></el-option>
                        <el-option label="降序" value="-1"></el-option>
                    </el-select>
                </el-form-item>
                <el-form-item label="优先级">
                    <el-input-number v-model="structDefine.columnPros.sortLevel" :min="1" :max="100" label="优先级"></el-input-number>
                </el-form-item>    
            </el-form>
            <span slot="footer" class="dialog-footer">
                <el-button @click="structDefine.updateColumnDialogVisible = false">取 消</el-button>
                <el-button type="primary" @click="updateColumn">确 定</el-button>
            </span>
        </el-dialog>
    </div>
</template>

<script>
import 'jquery'
import 'ztree'
import 'ztree/css/metroStyle/metroStyle.css'
const strChineseFirstPY = "YDYQSXMWZSSXJBYMGCCZQPSSQBYCDSCDQLDYLYBSSJGYZZJJFKCCLZDHWDWZJLJPFYYNWJJTMYHZWZHFLZPPQHGSCYYYNJQYXXGJHHSDSJNKKTMOMLCRXYPSNQSECCQZGGLLYJLMYZZSECYKYYHQWJSSGGYXYZYJWWKDJHYCHMYXJTLXJYQBYXZLDWRDJRWYSRLDZJPCBZJJBRCFTLECZSTZFXXZHTRQHYBDLYCZSSYMMRFMYQZPWWJJYFCRWFDFZQPYDDWYXKYJAWJFFXYPSFTZYHHYZYSWCJYXSCLCXXWZZXNBGNNXBXLZSZSBSGPYSYZDHMDZBQBZCWDZZYYTZHBTSYYBZGNTNXQYWQSKBPHHLXGYBFMJEBJHHGQTJCYSXSTKZHLYCKGLYSMZXYALMELDCCXGZYRJXSDLTYZCQKCNNJWHJTZZCQLJSTSTBNXBTYXCEQXGKWJYFLZQLYHYXSPSFXLMPBYSXXXYDJCZYLLLSJXFHJXPJBTFFYABYXBHZZBJYZLWLCZGGBTSSMDTJZXPTHYQTGLJSCQFZKJZJQNLZWLSLHDZBWJNCJZYZSQQYCQYRZCJJWYBRTWPYFTWEXCSKDZCTBZHYZZYYJXZCFFZZMJYXXSDZZOTTBZLQWFCKSZSXFYRLNYJMBDTHJXSQQCCSBXYYTSYFBXDZTGBCNSLCYZZPSAZYZZSCJCSHZQYDXLBPJLLMQXTYDZXSQJTZPXLCGLQTZWJBHCTSYJSFXYEJJTLBGXSXJMYJQQPFZASYJNTYDJXKJCDJSZCBARTDCLYJQMWNQNCLLLKBYBZZSYHQQLTWLCCXTXLLZNTYLNEWYZYXCZXXGRKRMTCNDNJTSYYSSDQDGHSDBJGHRWRQLYBGLXHLGTGXBQJDZPYJSJYJCTMRNYMGRZJCZGJMZMGXMPRYXKJNYMSGMZJYMKMFXMLDTGFBHCJHKYLPFMDXLQJJSMTQGZSJLQDLDGJYCALCMZCSDJLLNXDJFFFFJCZFMZFFPFKHKGDPSXKTACJDHHZDDCRRCFQYJKQCCWJDXHWJLYLLZGCFCQDSMLZPBJJPLSBCJGGDCKKDEZSQCCKJGCGKDJTJDLZYCXKLQSCGJCLTFPCQCZGWPJDQYZJJBYJHSJDZWGFSJGZKQCCZLLPSPKJGQJHZZLJPLGJGJJTHJJYJZCZMLZLYQBGJWMLJKXZDZNJQSYZMLJLLJKYWXMKJLHSKJGBMCLYYMKXJQLBMLLKMDXXKWYXYSLMLPSJQQJQXYXFJTJDXMXXLLCXQBSYJBGWYMBGGBCYXPJYGPEPFGDJGBHBNSQJYZJKJKHXQFGQZKFHYGKHDKLLSDJQXPQYKYBNQSXQNSZSWHBSXWHXWBZZXDMNSJBSBKBBZKLYLXGWXDRWYQZMYWSJQLCJXXJXKJEQXSCYETLZHLYYYSDZPAQYZCMTLSHTZCFYZYXYLJSDCJQAGYSLCQLYYYSHMRQQKLDXZSCSSSYDYCJYSFSJBFRSSZQSBXXPXJYSDRCKGJLGDKZJZBDKTCSYQPYHSTCLDJDHMXMCGXYZHJDDTMHLTXZXYLYMOHYJCLTYFBQQXPFBDFHHTKSQHZYYWCNXXCRWHOWGYJLEGWDQCWGFJYCSNTMYTOLBYGWQWESJPWNMLRYDZSZTXYQPZGCWXHNGPYXSHMYQJXZTDPPBFYHZHTJYFDZWKGKZBLDNTSXHQEEGZZYLZMMZYJZGXZXKHKSTXNXXWYLYAPSTHXDWHZYMPXAGKYDXBHNHXKDPJNMYHYLPMGOCSLNZHKXXLPZZLBMLSFBHHGYGYYGGBHSCYAQTYWLXTZQCEZYDQDQMMHTKLLSZHLSJZWFYHQSWSCWLQAZYNYTLSXTHAZNKZZSZZLAXXZWWCTGQQTDDYZTCCHYQZFLXPSLZYGPZSZNGLNDQTBDLXGTCTAJDKYWNSYZLJHHZZCWNYYZYWMHYCHHYXHJKZWSXHZYXLYSKQYSPSLYZWMYPPKBYGLKZHTYXAXQSYSHXASMCHKDSCRSWJPWXSGZJLWWSCHSJHSQNHCSEGNDAQTBAALZZMSSTDQJCJKTSCJAXPLGGXHHGXXZCXPDMMHLDGTYBYSJMXHMRCPXXJZCKZXSHMLQXXTTHXWZFKHCCZDYTCJYXQHLXDHYPJQXYLSYYDZOZJNYXQEZYSQYAYXWYPDGXDDXSPPYZNDLTWRHXYDXZZJHTCXMCZLHPYYYYMHZLLHNXMYLLLMDCPPXHMXDKYCYRDLTXJCHHZZXZLCCLYLNZSHZJZZLNNRLWHYQSNJHXYNTTTKYJPYCHHYEGKCTTWLGQRLGGTGTYGYHPYHYLQYQGCWYQKPYYYTTTTLHYHLLTYTTSPLKYZXGZWGPYDSSZZDQXSKCQNMJJZZBXYQMJRTFFBTKHZKBXLJJKDXJTLBWFZPPTKQTZTGPDGNTPJYFALQMKGXBDCLZFHZCLLLLADPMXDJHLCCLGYHDZFGYDDGCYYFGYDXKSSEBDHYKDKDKHNAXXYBPBYYHXZQGAFFQYJXDMLJCSQZLLPCHBSXGJYNDYBYQSPZWJLZKSDDTACTBXZDYZYPJZQSJNKKTKNJDJGYYPGTLFYQKASDNTCYHBLWDZHBBYDWJRYGKZYHEYYFJMSDTYFZJJHGCXPLXHLDWXXJKYTCYKSSSMTWCTTQZLPBSZDZWZXGZAGYKTYWXLHLSPBCLLOQMMZSSLCMBJCSZZKYDCZJGQQDSMCYTZQQLWZQZXSSFPTTFQMDDZDSHDTDWFHTDYZJYQJQKYPBDJYYXTLJHDRQXXXHAYDHRJLKLYTWHLLRLLRCXYLBWSRSZZSYMKZZHHKYHXKSMDSYDYCJPBZBSQLFCXXXNXKXWYWSDZYQOGGQMMYHCDZTTFJYYBGSTTTYBYKJDHKYXBELHTYPJQNFXFDYKZHQKZBYJTZBXHFDXKDASWTAWAJLDYJSFHBLDNNTNQJTJNCHXFJSRFWHZFMDRYJYJWZPDJKZYJYMPCYZNYNXFBYTFYFWYGDBNZZZDNYTXZEMMQBSQEHXFZMBMFLZZSRXYMJGSXWZJSPRYDJSJGXHJJGLJJYNZZJXHGXKYMLPYYYCXYTWQZSWHWLYRJLPXSLSXMFSWWKLCTNXNYNPSJSZHDZEPTXMYYWXYYSYWLXJQZQXZDCLEEELMCPJPCLWBXSQHFWWTFFJTNQJHJQDXHWLBYZNFJLALKYYJLDXHHYCSTYYWNRJYXYWTRMDRQHWQCMFJDYZMHMYYXJWMYZQZXTLMRSPWWCHAQBXYGZYPXYYRRCLMPYMGKSJSZYSRMYJSNXTPLNBAPPYPYLXYYZKYNLDZYJZCZNNLMZHHARQMPGWQTZMXXMLLHGDZXYHXKYXYCJMFFYYHJFSBSSQLXXNDYCANNMTCJCYPRRNYTYQNYYMBMSXNDLYLYSLJRLXYSXQMLLYZLZJJJKYZZCSFBZXXMSTBJGNXYZHLXNMCWSCYZYFZLXBRNNNYLBNRTGZQYSATSWRYHYJZMZDHZGZDWYBSSCSKXSYHYTXXGCQGXZZSHYXJSCRHMKKBXCZJYJYMKQHZJFNBHMQHYSNJNZYBKNQMCLGQHWLZNZSWXKHLJHYYBQLBFCDSXDLDSPFZPSKJYZWZXZDDXJSMMEGJSCSSMGCLXXKYYYLNYPWWWGYDKZJGGGZGGSYCKNJWNJPCXBJJTQTJWDSSPJXZXNZXUMELPXFSXTLLXCLJXJJLJZXCTPSWXLYDHLYQRWHSYCSQYYBYAYWJJJQFWQCQQCJQGXALDBZZYJGKGXPLTZYFXJLTPADKYQHPMATLCPDCKBMTXYBHKLENXDLEEGQDYMSAWHZMLJTWYGXLYQZLJEEYYBQQFFNLYXRDSCTGJGXYYNKLLYQKCCTLHJLQMKKZGCYYGLLLJDZGYDHZWXPYSJBZKDZGYZZHYWYFQYTYZSZYEZZLYMHJJHTSMQWYZLKYYWZCSRKQYTLTDXWCTYJKLWSQZWBDCQYNCJSRSZJLKCDCDTLZZZACQQZZDDXYPLXZBQJYLZLLLQDDZQJYJYJZYXNYYYNYJXKXDAZWYRDLJYYYRJLXLLDYXJCYWYWNQCCLDDNYYYNYCKCZHXXCCLGZQJGKWPPCQQJYSBZZXYJSQPXJPZBSBDSFNSFPZXHDWZTDWPPTFLZZBZDMYYPQJRSDZSQZSQXBDGCPZSWDWCSQZGMDHZXMWWFYBPDGPHTMJTHZSMMBGZMBZJCFZWFZBBZMQCFMBDMCJXLGPNJBBXGYHYYJGPTZGZMQBQTCGYXJXLWZKYDPDYMGCFTPFXYZTZXDZXTGKMTYBBCLBJASKYTSSQYYMSZXFJEWLXLLSZBQJJJAKLYLXLYCCTSXMCWFKKKBSXLLLLJYXTYLTJYYTDPJHNHNNKBYQNFQYYZBYYESSESSGDYHFHWTCJBSDZZTFDMXHCNJZYMQWSRYJDZJQPDQBBSTJGGFBKJBXTGQHNGWJXJGDLLTHZHHYYYYYYSXWTYYYCCBDBPYPZYCCZYJPZYWCBDLFWZCWJDXXHYHLHWZZXJTCZLCDPXUJCZZZLYXJJTXPHFXWPYWXZPTDZZBDZCYHJHMLXBQXSBYLRDTGJRRCTTTHYTCZWMXFYTWWZCWJWXJYWCSKYBZSCCTZQNHXNWXXKHKFHTSWOCCJYBCMPZZYKBNNZPBZHHZDLSYDDYTYFJPXYNGFXBYQXCBHXCPSXTYZDMKYSNXSXLHKMZXLYHDHKWHXXSSKQYHHCJYXGLHZXCSNHEKDTGZXQYPKDHEXTYKCNYMYYYPKQYYYKXZLTHJQTBYQHXBMYHSQCKWWYLLHCYYLNNEQXQWMCFBDCCMLJGGXDQKTLXKGNQCDGZJWYJJLYHHQTTTNWCHMXCXWHWSZJYDJCCDBQCDGDNYXZTHCQRXCBHZTQCBXWGQWYYBXHMBYMYQTYEXMQKYAQYRGYZSLFYKKQHYSSQYSHJGJCNXKZYCXSBXYXHYYLSTYCXQTHYSMGSCPMMGCCCCCMTZTASMGQZJHKLOSQYLSWTMXSYQKDZLJQQYPLSYCZTCQQPBBQJZCLPKHQZYYXXDTDDTSJCXFFLLCHQXMJLWCJCXTSPYCXNDTJSHJWXDQQJSKXYAMYLSJHMLALYKXCYYDMNMDQMXMCZNNCYBZKKYFLMCHCMLHXRCJJHSYLNMTJZGZGYWJXSRXCWJGJQHQZDQJDCJJZKJKGDZQGJJYJYLXZXXCDQHHHEYTMHLFSBDJSYYSHFYSTCZQLPBDRFRZTZYKYWHSZYQKWDQZRKMSYNBCRXQBJYFAZPZZEDZCJYWBCJWHYJBQSZYWRYSZPTDKZPFPBNZTKLQYHBBZPNPPTYZZYBQNYDCPJMMCYCQMCYFZZDCMNLFPBPLNGQJTBTTNJZPZBBZNJKLJQYLNBZQHKSJZNGGQSZZKYXSHPZSNBCGZKDDZQANZHJKDRTLZLSWJLJZLYWTJNDJZJHXYAYNCBGTZCSSQMNJPJYTYSWXZFKWJQTKHTZPLBHSNJZSYZBWZZZZLSYLSBJHDWWQPSLMMFBJDWAQYZTCJTBNNWZXQXCDSLQGDSDPDZHJTQQPSWLYYJZLGYXYZLCTCBJTKTYCZJTQKBSJLGMGZDMCSGPYNJZYQYYKNXRPWSZXMTNCSZZYXYBYHYZAXYWQCJTLLCKJJTJHGDXDXYQYZZBYWDLWQCGLZGJGQRQZCZSSBCRPCSKYDZNXJSQGXSSJMYDNSTZTPBDLTKZWXQWQTZEXNQCZGWEZKSSBYBRTSSSLCCGBPSZQSZLCCGLLLZXHZQTHCZMQGYZQZNMCOCSZJMMZSQPJYGQLJYJPPLDXRGZYXCCSXHSHGTZNLZWZKJCXTCFCJXLBMQBCZZWPQDNHXLJCTHYZLGYLNLSZZPCXDSCQQHJQKSXZPBAJYEMSMJTZDXLCJYRYYNWJBNGZZTMJXLTBSLYRZPYLSSCNXPHLLHYLLQQZQLXYMRSYCXZLMMCZLTZSDWTJJLLNZGGQXPFSKYGYGHBFZPDKMWGHCXMSGDXJMCJZDYCABXJDLNBCDQYGSKYDQTXDJJYXMSZQAZDZFSLQXYJSJZYLBTXXWXQQZBJZUFBBLYLWDSLJHXJYZJWTDJCZFQZQZZDZSXZZQLZCDZFJHYSPYMPQZMLPPLFFXJJNZZYLSJEYQZFPFZKSYWJJJHRDJZZXTXXGLGHYDXCSKYSWMMZCWYBAZBJKSHFHJCXMHFQHYXXYZFTSJYZFXYXPZLCHMZMBXHZZSXYFYMNCWDABAZLXKTCSHHXKXJJZJSTHYGXSXYYHHHJWXKZXSSBZZWHHHCWTZZZPJXSNXQQJGZYZYWLLCWXZFXXYXYHXMKYYSWSQMNLNAYCYSPMJKHWCQHYLAJJMZXHMMCNZHBHXCLXTJPLTXYJHDYYLTTXFSZHYXXSJBJYAYRSMXYPLCKDUYHLXRLNLLSTYZYYQYGYHHSCCSMZCTZQXKYQFPYYRPFFLKQUNTSZLLZMWWTCQQYZWTLLMLMPWMBZSSTZRBPDDTLQJJBXZCSRZQQYGWCSXFWZLXCCRSZDZMCYGGDZQSGTJSWLJMYMMZYHFBJDGYXCCPSHXNZCSBSJYJGJMPPWAFFYFNXHYZXZYLREMZGZCYZSSZDLLJCSQFNXZKPTXZGXJJGFMYYYSNBTYLBNLHPFZDCYFBMGQRRSSSZXYSGTZRNYDZZCDGPJAFJFZKNZBLCZSZPSGCYCJSZLMLRSZBZZLDLSLLYSXSQZQLYXZLSKKBRXBRBZCYCXZZZEEYFGKLZLYYHGZSGZLFJHGTGWKRAAJYZKZQTSSHJJXDCYZUYJLZYRZDQQHGJZXSSZBYKJPBFRTJXLLFQWJHYLQTYMBLPZDXTZYGBDHZZRBGXHWNJTJXLKSCFSMWLSDQYSJTXKZSCFWJLBXFTZLLJZLLQBLSQMQQCGCZFPBPHZCZJLPYYGGDTGWDCFCZQYYYQYSSCLXZSKLZZZGFFCQNWGLHQYZJJCZLQZZYJPJZZBPDCCMHJGXDQDGDLZQMFGPSYTSDYFWWDJZJYSXYYCZCYHZWPBYKXRYLYBHKJKSFXTZJMMCKHLLTNYYMSYXYZPYJQYCSYCWMTJJKQYRHLLQXPSGTLYYCLJSCPXJYZFNMLRGJJTYZBXYZMSJYJHHFZQMSYXRSZCWTLRTQZSSTKXGQKGSPTGCZNJSJCQCXHMXGGZTQYDJKZDLBZSXJLHYQGGGTHQSZPYHJHHGYYGKGGCWJZZYLCZLXQSFTGZSLLLMLJSKCTBLLZZSZMMNYTPZSXQHJCJYQXYZXZQZCPSHKZZYSXCDFGMWQRLLQXRFZTLYSTCTMJCXJJXHJNXTNRZTZFQYHQGLLGCXSZSJDJLJCYDSJTLNYXHSZXCGJZYQPYLFHDJSBPCCZHJJJQZJQDYBSSLLCMYTTMQTBHJQNNYGKYRQYQMZGCJKPDCGMYZHQLLSLLCLMHOLZGDYYFZSLJCQZLYLZQJESHNYLLJXGJXLYSYYYXNBZLJSSZCQQCJYLLZLTJYLLZLLBNYLGQCHXYYXOXCXQKYJXXXYKLXSXXYQXCYKQXQCSGYXXYQXYGYTQOHXHXPYXXXULCYEYCHZZCBWQBBWJQZSCSZSSLZYLKDESJZWMYMCYTSDSXXSCJPQQSQYLYYZYCMDJDZYWCBTJSYDJKCYDDJLBDJJSODZYSYXQQYXDHHGQQYQHDYXWGMMMAJDYBBBPPBCMUUPLJZSMTXERXJMHQNUTPJDCBSSMSSSTKJTSSMMTRCPLZSZMLQDSDMJMQPNQDXCFYNBFSDQXYXHYAYKQYDDLQYYYSSZBYDSLNTFQTZQPZMCHDHCZCWFDXTMYQSPHQYYXSRGJCWTJTZZQMGWJJTJHTQJBBHWZPXXHYQFXXQYWYYHYSCDYDHHQMNMTMWCPBSZPPZZGLMZFOLLCFWHMMSJZTTDHZZYFFYTZZGZYSKYJXQYJZQBHMBZZLYGHGFMSHPZFZSNCLPBQSNJXZSLXXFPMTYJYGBXLLDLXPZJYZJYHHZCYWHJYLSJEXFSZZYWXKZJLUYDTMLYMQJPWXYHXSKTQJEZRPXXZHHMHWQPWQLYJJQJJZSZCPHJLCHHNXJLQWZJHBMZYXBDHHYPZLHLHLGFWLCHYYTLHJXCJMSCPXSTKPNHQXSRTYXXTESYJCTLSSLSTDLLLWWYHDHRJZSFGXTSYCZYNYHTDHWJSLHTZDQDJZXXQHGYLTZPHCSQFCLNJTCLZPFSTPDYNYLGMJLLYCQHYSSHCHYLHQYQTMZYPBYWRFQYKQSYSLZDQJMPXYYSSRHZJNYWTQDFZBWWTWWRXCWHGYHXMKMYYYQMSMZHNGCEPMLQQMTCWCTMMPXJPJJHFXYYZSXZHTYBMSTSYJTTQQQYYLHYNPYQZLCYZHZWSMYLKFJXLWGXYPJYTYSYXYMZCKTTWLKSMZSYLMPWLZWXWQZSSAQSYXYRHSSNTSRAPXCPWCMGDXHXZDZYFJHGZTTSBJHGYZSZYSMYCLLLXBTYXHBBZJKSSDMALXHYCFYGMQYPJYCQXJLLLJGSLZGQLYCJCCZOTYXMTMTTLLWTGPXYMZMKLPSZZZXHKQYSXCTYJZYHXSHYXZKXLZWPSQPYHJWPJPWXQQYLXSDHMRSLZZYZWTTCYXYSZZSHBSCCSTPLWSSCJCHNLCGCHSSPHYLHFHHXJSXYLLNYLSZDHZXYLSXLWZYKCLDYAXZCMDDYSPJTQJZLNWQPSSSWCTSTSZLBLNXSMNYYMJQBQHRZWTYYDCHQLXKPZWBGQYBKFCMZWPZLLYYLSZYDWHXPSBCMLJBSCGBHXLQHYRLJXYSWXWXZSLDFHLSLYNJLZYFLYJYCDRJLFSYZFSLLCQYQFGJYHYXZLYLMSTDJCYHBZLLNWLXXYGYYHSMGDHXXHHLZZJZXCZZZCYQZFNGWPYLCPKPYYPMCLQKDGXZGGWQBDXZZKZFBXXLZXJTPJPTTBYTSZZDWSLCHZHSLTYXHQLHYXXXYYZYSWTXZKHLXZXZPYHGCHKCFSYHUTJRLXFJXPTZTWHPLYXFCRHXSHXKYXXYHZQDXQWULHYHMJTBFLKHTXCWHJFWJCFPQRYQXCYYYQYGRPYWSGSUNGWCHKZDXYFLXXHJJBYZWTSXXNCYJJYMSWZJQRMHXZWFQSYLZJZGBHYNSLBGTTCSYBYXXWXYHXYYXNSQYXMQYWRGYQLXBBZLJSYLPSYTJZYHYZAWLRORJMKSCZJXXXYXCHDYXRYXXJDTSQFXLYLTSFFYXLMTYJMJUYYYXLTZCSXQZQHZXLYYXZHDNBRXXXJCTYHLBRLMBRLLAXKYLLLJLYXXLYCRYLCJTGJCMTLZLLCYZZPZPCYAWHJJFYBDYYZSMPCKZDQYQPBPCJPDCYZMDPBCYYDYCNNPLMTMLRMFMMGWYZBSJGYGSMZQQQZTXMKQWGXLLPJGZBQCDJJJFPKJKCXBLJMSWMDTQJXLDLPPBXCWRCQFBFQJCZAHZGMYKPHYYHZYKNDKZMBPJYXPXYHLFPNYYGXJDBKXNXHJMZJXSTRSTLDXSKZYSYBZXJLXYSLBZYSLHXJPFXPQNBYLLJQKYGZMCYZZYMCCSLCLHZFWFWYXZMWSXTYNXJHPYYMCYSPMHYSMYDYSHQYZCHMJJMZCAAGCFJBBHPLYZYLXXSDJGXDHKXXTXXNBHRMLYJSLTXMRHNLXQJXYZLLYSWQGDLBJHDCGJYQYCMHWFMJYBMBYJYJWYMDPWHXQLDYGPDFXXBCGJSPCKRSSYZJMSLBZZJFLJJJLGXZGYXYXLSZQYXBEXYXHGCXBPLDYHWETTWWCJMBTXCHXYQXLLXFLYXLLJLSSFWDPZSMYJCLMWYTCZPCHQEKCQBWLCQYDPLQPPQZQFJQDJHYMMCXTXDRMJWRHXCJZYLQXDYYNHYYHRSLSRSYWWZJYMTLTLLGTQCJZYABTCKZCJYCCQLJZQXALMZYHYWLWDXZXQDLLQSHGPJFJLJHJABCQZDJGTKHSSTCYJLPSWZLXZXRWGLDLZRLZXTGSLLLLZLYXXWGDZYGBDPHZPBRLWSXQBPFDWOFMWHLYPCBJCCLDMBZPBZZLCYQXLDOMZBLZWPDWYYGDSTTHCSQSCCRSSSYSLFYBFNTYJSZDFNDPDHDZZMBBLSLCMYFFGTJJQWFTMTPJWFNLBZCMMJTGBDZLQLPYFHYYMJYLSDCHDZJWJCCTLJCLDTLJJCPDDSQDSSZYBNDBJLGGJZXSXNLYCYBJXQYCBYLZCFZPPGKCXZDZFZTJJFJSJXZBNZYJQTTYJYHTYCZHYMDJXTTMPXSPLZCDWSLSHXYPZGTFMLCJTYCBPMGDKWYCYZCDSZZYHFLYCTYGWHKJYYLSJCXGYWJCBLLCSNDDBTZBSCLYZCZZSSQDLLMQYYHFSLQLLXFTYHABXGWNYWYYPLLSDLDLLBJCYXJZMLHLJDXYYQYTDLLLBUGBFDFBBQJZZMDPJHGCLGMJJPGAEHHBWCQXAXHHHZCHXYPHJAXHLPHJPGPZJQCQZGJJZZUZDMQYYBZZPHYHYBWHAZYJHYKFGDPFQSDLZMLJXKXGALXZDAGLMDGXMWZQYXXDXXPFDMMSSYMPFMDMMKXKSYZYSHDZKXSYSMMZZZMSYDNZZCZXFPLSTMZDNMXCKJMZTYYMZMZZMSXHHDCZJEMXXKLJSTLWLSQLYJZLLZJSSDPPMHNLZJCZYHMXXHGZCJMDHXTKGRMXFWMCGMWKDTKSXQMMMFZZYDKMSCLCMPCGMHSPXQPZDSSLCXKYXTWLWJYAHZJGZQMCSNXYYMMPMLKJXMHLMLQMXCTKZMJQYSZJSYSZHSYJZJCDAJZYBSDQJZGWZQQXFKDMSDJLFWEHKZQKJPEYPZYSZCDWYJFFMZZYLTTDZZEFMZLBNPPLPLPEPSZALLTYLKCKQZKGENQLWAGYXYDPXLHSXQQWQCQXQCLHYXXMLYCCWLYMQYSKGCHLCJNSZKPYZKCQZQLJPDMDZHLASXLBYDWQLWDNBQCRYDDZTJYBKBWSZDXDTNPJDTCTQDFXQQMGNXECLTTBKPWSLCTYQLPWYZZKLPYGZCQQPLLKCCYLPQMZCZQCLJSLQZDJXLDDHPZQDLJJXZQDXYZQKZLJCYQDYJPPYPQYKJYRMPCBYMCXKLLZLLFQPYLLLMBSGLCYSSLRSYSQTMXYXZQZFDZUYSYZTFFMZZSMZQHZSSCCMLYXWTPZGXZJGZGSJSGKDDHTQGGZLLBJDZLCBCHYXYZHZFYWXYZYMSDBZZYJGTSMTFXQYXQSTDGSLNXDLRYZZLRYYLXQHTXSRTZNGZXBNQQZFMYKMZJBZYMKBPNLYZPBLMCNQYZZZSJZHJCTZKHYZZJRDYZHNPXGLFZTLKGJTCTSSYLLGZRZBBQZZKLPKLCZYSSUYXBJFPNJZZXCDWXZYJXZZDJJKGGRSRJKMSMZJLSJYWQSKYHQJSXPJZZZLSNSHRNYPZTWCHKLPSRZLZXYJQXQKYSJYCZTLQZYBBYBWZPQDWWYZCYTJCJXCKCWDKKZXSGKDZXWWYYJQYYTCYTDLLXWKCZKKLCCLZCQQDZLQLCSFQCHQHSFSMQZZLNBJJZBSJHTSZDYSJQJPDLZCDCWJKJZZLPYCGMZWDJJBSJQZSYZYHHXJPBJYDSSXDZNCGLQMBTSFSBPDZDLZNFGFJGFSMPXJQLMBLGQCYYXBQKDJJQYRFKZTJDHCZKLBSDZCFJTPLLJGXHYXZCSSZZXSTJYGKGCKGYOQXJPLZPBPGTGYJZGHZQZZLBJLSQFZGKQQJZGYCZBZQTLDXRJXBSXXPZXHYZYCLWDXJJHXMFDZPFZHQHQMQGKSLYHTYCGFRZGNQXCLPDLBZCSCZQLLJBLHBZCYPZZPPDYMZZSGYHCKCPZJGSLJLNSCDSLDLXBMSTLDDFJMKDJDHZLZXLSZQPQPGJLLYBDSZGQLBZLSLKYYHZTTNTJYQTZZPSZQZTLLJTYYLLQLLQYZQLBDZLSLYYZYMDFSZSNHLXZNCZQZPBWSKRFBSYZMTHBLGJPMCZZLSTLXSHTCSYZLZBLFEQHLXFLCJLYLJQCBZLZJHHSSTBRMHXZHJZCLXFNBGXGTQJCZTMSFZKJMSSNXLJKBHSJXNTNLZDNTLMSJXGZJYJCZXYJYJWRWWQNZTNFJSZPZSHZJFYRDJSFSZJZBJFZQZZHZLXFYSBZQLZSGYFTZDCSZXZJBQMSZKJRHYJZCKMJKHCHGTXKXQGLXPXFXTRTYLXJXHDTSJXHJZJXZWZLCQSBTXWXGXTXXHXFTSDKFJHZYJFJXRZSDLLLTQSQQZQWZXSYQTWGWBZCGZLLYZBCLMQQTZHZXZXLJFRMYZFLXYSQXXJKXRMQDZDMMYYBSQBHGZMWFWXGMXLZPYYTGZYCCDXYZXYWGSYJYZNBHPZJSQSYXSXRTFYZGRHZTXSZZTHCBFCLSYXZLZQMZLMPLMXZJXSFLBYZMYQHXJSXRXSQZZZSSLYFRCZJRCRXHHZXQYDYHXSJJHZCXZBTYNSYSXJBQLPXZQPYMLXZKYXLXCJLCYSXXZZLXDLLLJJYHZXGYJWKJRWYHCPSGNRZLFZWFZZNSXGXFLZSXZZZBFCSYJDBRJKRDHHGXJLJJTGXJXXSTJTJXLYXQFCSGSWMSBCTLQZZWLZZKXJMLTMJYHSDDBXGZHDLBMYJFRZFSGCLYJBPMLYSMSXLSZJQQHJZFXGFQFQBPXZGYYQXGZTCQWYLTLGWSGWHRLFSFGZJMGMGBGTJFSYZZGZYZAFLSSPMLPFLCWBJZCLJJMZLPJJLYMQDMYYYFBGYGYZMLYZDXQYXRQQQHSYYYQXYLJTYXFSFSLLGNQCYHYCWFHCCCFXPYLYPLLZYXXXXXKQHHXSHJZCFZSCZJXCPZWHHHHHAPYLQALPQAFYHXDYLUKMZQGGGDDESRNNZLTZGCHYPPYSQJJHCLLJTOLNJPZLJLHYMHEYDYDSQYCDDHGZUNDZCLZYZLLZNTNYZGSLHSLPJJBDGWXPCDUTJCKLKCLWKLLCASSTKZZDNQNTTLYYZSSYSSZZRYLJQKCQDHHCRXRZYDGRGCWCGZQFFFPPJFZYNAKRGYWYQPQXXFKJTSZZXSWZDDFBBXTBGTZKZNPZZPZXZPJSZBMQHKCYXYLDKLJNYPKYGHGDZJXXEAHPNZKZTZCMXCXMMJXNKSZQNMNLWBWWXJKYHCPSTMCSQTZJYXTPCTPDTNNPGLLLZSJLSPBLPLQHDTNJNLYYRSZFFJFQWDPHZDWMRZCCLODAXNSSNYZRESTYJWJYJDBCFXNMWTTBYLWSTSZGYBLJPXGLBOCLHPCBJLTMXZLJYLZXCLTPNCLCKXTPZJSWCYXSFYSZDKNTLBYJCYJLLSTGQCBXRYZXBXKLYLHZLQZLNZCXWJZLJZJNCJHXMNZZGJZZXTZJXYCYYCXXJYYXJJXSSSJSTSSTTPPGQTCSXWZDCSYFPTFBFHFBBLZJCLZZDBXGCXLQPXKFZFLSYLTUWBMQJHSZBMDDBCYSCCLDXYCDDQLYJJWMQLLCSGLJJSYFPYYCCYLTJANTJJPWYCMMGQYYSXDXQMZHSZXPFTWWZQSWQRFKJLZJQQYFBRXJHHFWJJZYQAZMYFRHCYYBYQWLPEXCCZSTYRLTTDMQLYKMBBGMYYJPRKZNPBSXYXBHYZDJDNGHPMFSGMWFZMFQMMBCMZZCJJLCNUXYQLMLRYGQZCYXZLWJGCJCGGMCJNFYZZJHYCPRRCMTZQZXHFQGTJXCCJEAQCRJYHPLQLSZDJRBCQHQDYRHYLYXJSYMHZYDWLDFRYHBPYDTSSCNWBXGLPZMLZZTQSSCPJMXXYCSJYTYCGHYCJWYRXXLFEMWJNMKLLSWTXHYYYNCMMCWJDQDJZGLLJWJRKHPZGGFLCCSCZMCBLTBHBQJXQDSPDJZZGKGLFQYWBZYZJLTSTDHQHCTCBCHFLQMPWDSHYYTQWCNZZJTLBYMBPDYYYXSQKXWYYFLXXNCWCXYPMAELYKKJMZZZBRXYYQJFLJPFHHHYTZZXSGQQMHSPGDZQWBWPJHZJDYSCQWZKTXXSQLZYYMYSDZGRXCKKUJLWPYSYSCSYZLRMLQSYLJXBCXTLWDQZPCYCYKPPPNSXFYZJJRCEMHSZMSXLXGLRWGCSTLRSXBZGBZGZTCPLUJLSLYLYMTXMTZPALZXPXJTJWTCYYZLBLXBZLQMYLXPGHDSLSSDMXMBDZZSXWHAMLCZCPJMCNHJYSNSYGCHSKQMZZQDLLKABLWJXSFMOCDXJRRLYQZKJMYBYQLYHETFJZFRFKSRYXFJTWDSXXSYSQJYSLYXWJHSNLXYYXHBHAWHHJZXWMYLJCSSLKYDZTXBZSYFDXGXZJKHSXXYBSSXDPYNZWRPTQZCZENYGCXQFJYKJBZMLJCMQQXUOXSLYXXLYLLJDZBTYMHPFSTTQQWLHOKYBLZZALZXQLHZWRRQHLSTMYPYXJJXMQSJFNBXYXYJXXYQYLTHYLQYFMLKLJTMLLHSZWKZHLJMLHLJKLJSTLQXYLMBHHLNLZXQJHXCFXXLHYHJJGBYZZKBXSCQDJQDSUJZYYHZHHMGSXCSYMXFEBCQWWRBPYYJQTYZCYQYQQZYHMWFFHGZFRJFCDPXNTQYZPDYKHJLFRZXPPXZDBBGZQSTLGDGYLCQMLCHHMFYWLZYXKJLYPQHSYWMQQGQZMLZJNSQXJQSYJYCBEHSXFSZPXZWFLLBCYYJDYTDTHWZSFJMQQYJLMQXXLLDTTKHHYBFPWTYYSQQWNQWLGWDEBZWCMYGCULKJXTMXMYJSXHYBRWFYMWFRXYQMXYSZTZZTFYKMLDHQDXWYYNLCRYJBLPSXCXYWLSPRRJWXHQYPHTYDNXHHMMYWYTZCSQMTSSCCDALWZTCPQPYJLLQZYJSWXMZZMMYLMXCLMXCZMXMZSQTZPPQQBLPGXQZHFLJJHYTJSRXWZXSCCDLXTYJDCQJXSLQYCLZXLZZXMXQRJMHRHZJBHMFLJLMLCLQNLDXZLLLPYPSYJYSXCQQDCMQJZZXHNPNXZMEKMXHYKYQLXSXTXJYYHWDCWDZHQYYBGYBCYSCFGPSJNZDYZZJZXRZRQJJYMCANYRJTLDPPYZBSTJKXXZYPFDWFGZZRPYMTNGXZQBYXNBUFNQKRJQZMJEGRZGYCLKXZDSKKNSXKCLJSPJYYZLQQJYBZSSQLLLKJXTBKTYLCCDDBLSPPFYLGYDTZJYQGGKQTTFZXBDKTYYHYBBFYTYYBCLPDYTGDHRYRNJSPTCSNYJQHKLLLZSLYDXXWBCJQSPXBPJZJCJDZFFXXBRMLAZHCSNDLBJDSZBLPRZTSWSBXBCLLXXLZDJZSJPYLYXXYFTFFFBHJJXGBYXJPMMMPSSJZJMTLYZJXSWXTYLEDQPJMYGQZJGDJLQJWJQLLSJGJGYGMSCLJJXDTYGJQJQJCJZCJGDZZSXQGSJGGCXHQXSNQLZZBXHSGZXCXYLJXYXYYDFQQJHJFXDHCTXJYRXYSQTJXYEFYYSSYYJXNCYZXFXMSYSZXYYSCHSHXZZZGZZZGFJDLTYLNPZGYJYZYYQZPBXQBDZTZCZYXXYHHSQXSHDHGQHJHGYWSZTMZMLHYXGEBTYLZKQWYTJZRCLEKYSTDBCYKQQSAYXCJXWWGSBHJYZYDHCSJKQCXSWXFLTYNYZPZCCZJQTZWJQDZZZQZLJJXLSBHPYXXPSXSHHEZTXFPTLQYZZXHYTXNCFZYYHXGNXMYWXTZSJPTHHGYMXMXQZXTSBCZYJYXXTYYZYPCQLMMSZMJZZLLZXGXZAAJZYXJMZXWDXZSXZDZXLEYJJZQBHZWZZZQTZPSXZTDSXJJJZNYAZPHXYYSRNQDTHZHYYKYJHDZXZLSWCLYBZYECWCYCRYLCXNHZYDZYDYJDFRJJHTRSQTXYXJRJHOJYNXELXSFSFJZGHPZSXZSZDZCQZBYYKLSGSJHCZSHDGQGXYZGXCHXZJWYQWGYHKSSEQZZNDZFKWYSSTCLZSTSYMCDHJXXYWEYXCZAYDMPXMDSXYBSQMJMZJMTZQLPJYQZCGQHXJHHLXXHLHDLDJQCLDWBSXFZZYYSCHTYTYYBHECXHYKGJPXHHYZJFXHWHBDZFYZBCAPNPGNYDMSXHMMMMAMYNBYJTMPXYYMCTHJBZYFCGTYHWPHFTWZZEZSBZEGPFMTSKFTYCMHFLLHGPZJXZJGZJYXZSBBQSCZZLZCCSTPGXMJSFTCCZJZDJXCYBZLFCJSYZFGSZLYBCWZZBYZDZYPSWYJZXZBDSYUXLZZBZFYGCZXBZHZFTPBGZGEJBSTGKDMFHYZZJHZLLZZGJQZLSFDJSSCBZGPDLFZFZSZYZYZSYGCXSNXXCHCZXTZZLJFZGQSQYXZJQDCCZTQCDXZJYQJQCHXZTDLGSCXZSYQJQTZWLQDQZTQCHQQJZYEZZZPBWKDJFCJPZTYPQYQTTYNLMBDKTJZPQZQZZFPZSBNJLGYJDXJDZZKZGQKXDLPZJTCJDQBXDJQJSTCKNXBXZMSLYJCQMTJQWWCJQNJNLLLHJCWQTBZQYDZCZPZZDZYDDCYZZZCCJTTJFZDPRRTZTJDCQTQZDTJNPLZBCLLCTZSXKJZQZPZLBZRBTJDCXFCZDBCCJJLTQQPLDCGZDBBZJCQDCJWYNLLZYZCCDWLLXWZLXRXNTQQCZXKQLSGDFQTDDGLRLAJJTKUYMKQLLTZYTDYYCZGJWYXDXFRSKSTQTENQMRKQZHHQKDLDAZFKYPBGGPZREBZZYKZZSPEGJXGYKQZZZSLYSYYYZWFQZYLZZLZHWCHKYPQGNPGBLPLRRJYXCCSYYHSFZFYBZYYTGZXYLXCZWXXZJZBLFFLGSKHYJZEYJHLPLLLLCZGXDRZELRHGKLZZYHZLYQSZZJZQLJZFLNBHGWLCZCFJYSPYXZLZLXGCCPZBLLCYBBBBUBBCBPCRNNZCZYRBFSRLDCGQYYQXYGMQZWTZYTYJXYFWTEHZZJYWLCCNTZYJJZDEDPZDZTSYQJHDYMBJNYJZLXTSSTPHNDJXXBYXQTZQDDTJTDYYTGWSCSZQFLSHLGLBCZPHDLYZJYCKWTYTYLBNYTSDSYCCTYSZYYEBHEXHQDTWNYGYCLXTSZYSTQMYGZAZCCSZZDSLZCLZRQXYYELJSBYMXSXZTEMBBLLYYLLYTDQYSHYMRQWKFKBFXNXSBYCHXBWJYHTQBPBSBWDZYLKGZSKYHXQZJXHXJXGNLJKZLYYCDXLFYFGHLJGJYBXQLYBXQPQGZTZPLNCYPXDJYQYDYMRBESJYYHKXXSTMXRCZZYWXYQYBMCLLYZHQYZWQXDBXBZWZMSLPDMYSKFMZKLZCYQYCZLQXFZZYDQZPZYGYJYZMZXDZFYFYTTQTZHGSPCZMLCCYTZXJCYTJMKSLPZHYSNZLLYTPZCTZZCKTXDHXXTQCYFKSMQCCYYAZHTJPCYLZLYJBJXTPNYLJYYNRXSYLMMNXJSMYBCSYSYLZYLXJJQYLDZLPQBFZZBLFNDXQKCZFYWHGQMRDSXYCYTXNQQJZYYPFZXDYZFPRXEJDGYQBXRCNFYYQPGHYJDYZXGRHTKYLNWDZNTSMPKLBTHBPYSZBZTJZSZZJTYYXZPHSSZZBZCZPTQFZMYFLYPYBBJQXZMXXDJMTSYSKKBJZXHJCKLPSMKYJZCXTMLJYXRZZQSLXXQPYZXMKYXXXJCLJPRMYYGADYSKQLSNDHYZKQXZYZTCGHZTLMLWZYBWSYCTBHJHJFCWZTXWYTKZLXQSHLYJZJXTMPLPYCGLTBZZTLZJCYJGDTCLKLPLLQPJMZPAPXYZLKKTKDZCZZBNZDYDYQZJYJGMCTXLTGXSZLMLHBGLKFWNWZHDXUHLFMKYSLGXDTWWFRJEJZTZHYDXYKSHWFZCQSHKTMQQHTZHYMJDJSKHXZJZBZZXYMPAGQMSTPXLSKLZYNWRTSQLSZBPSPSGZWYHTLKSSSWHZZLYYTNXJGMJSZSUFWNLSOZTXGXLSAMMLBWLDSZYLAKQCQCTMYCFJBSLXCLZZCLXXKSBZQCLHJPSQPLSXXCKSLNHPSFQQYTXYJZLQLDXZQJZDYYDJNZPTUZDSKJFSLJHYLZSQZLBTXYDGTQFDBYAZXDZHZJNHHQBYKNXJJQCZMLLJZKSPLDYCLBBLXKLELXJLBQYCXJXGCNLCQPLZLZYJTZLJGYZDZPLTQCSXFDMNYCXGBTJDCZNBGBQYQJWGKFHTNPYQZQGBKPBBYZMTJDYTBLSQMPSXTBNPDXKLEMYYCJYNZCTLDYKZZXDDXHQSHDGMZSJYCCTAYRZLPYLTLKXSLZCGGEXCLFXLKJRTLQJAQZNCMBYDKKCXGLCZJZXJHPTDJJMZQYKQSECQZDSHHADMLZFMMZBGNTJNNLGBYJBRBTMLBYJDZXLCJLPLDLPCQDHLXZLYCBLCXZZJADJLNZMMSSSMYBHBSQKBHRSXXJMXSDZNZPXLGBRHWGGFCXGMSKLLTSJYYCQLTSKYWYYHYWXBXQYWPYWYKQLSQPTNTKHQCWDQKTWPXXHCPTHTWUMSSYHBWCRWXHJMKMZNGWTMLKFGHKJYLSYYCXWHYECLQHKQHTTQKHFZLDXQWYZYYDESBPKYRZPJFYYZJCEQDZZDLATZBBFJLLCXDLMJSSXEGYGSJQXCWBXSSZPDYZCXDNYXPPZYDLYJCZPLTXLSXYZYRXCYYYDYLWWNZSAHJSYQYHGYWWAXTJZDAXYSRLTDPSSYYFNEJDXYZHLXLLLZQZSJNYQYQQXYJGHZGZCYJCHZLYCDSHWSHJZYJXCLLNXZJJYYXNFXMWFPYLCYLLABWDDHWDXJMCXZTZPMLQZHSFHZYNZTLLDYWLSLXHYMMYLMBWWKYXYADTXYLLDJPYBPWUXJMWMLLSAFDLLYFLBHHHBQQLTZJCQJLDJTFFKMMMBYTHYGDCQRDDWRQJXNBYSNWZDBYYTBJHPYBYTTJXAAHGQDQTMYSTQXKBTZPKJLZRBEQQSSMJJBDJOTGTBXPGBKTLHQXJJJCTHXQDWJLWRFWQGWSHCKRYSWGFTGYGBXSDWDWRFHWYTJJXXXJYZYSLPYYYPAYXHYDQKXSHXYXGSKQHYWFDDDPPLCJLQQEEWXKSYYKDYPLTJTHKJLTCYYHHJTTPLTZZCDLTHQKZXQYSTEEYWYYZYXXYYSTTJKLLPZMCYHQGXYHSRMBXPLLNQYDQHXSXXWGDQBSHYLLPJJJTHYJKYPPTHYYKTYEZYENMDSHLCRPQFDGFXZPSFTLJXXJBSWYYSKSFLXLPPLBBBLBSFXFYZBSJSSYLPBBFFFFSSCJDSTZSXZRYYSYFFSYZYZBJTBCTSBSDHRTJJBYTCXYJEYLXCBNEBJDSYXYKGSJZBXBYTFZWGENYHHTHZHHXFWGCSTBGXKLSXYWMTMBYXJSTZSCDYQRCYTWXZFHMYMCXLZNSDJTTTXRYCFYJSBSDYERXJLJXBBDEYNJGHXGCKGSCYMBLXJMSZNSKGXFBNBPTHFJAAFXYXFPXMYPQDTZCXZZPXRSYWZDLYBBKTYQPQJPZYPZJZNJPZJLZZFYSBTTSLMPTZRTDXQSJEHBZYLZDHLJSQMLHTXTJECXSLZZSPKTLZKQQYFSYGYWPCPQFHQHYTQXZKRSGTTSQCZLPTXCDYYZXSQZSLXLZMYCPCQBZYXHBSXLZDLTCDXTYLZJYYZPZYZLTXJSJXHLPMYTXCQRBLZSSFJZZTNJYTXMYJHLHPPLCYXQJQQKZZSCPZKSWALQSBLCCZJSXGWWWYGYKTJBBZTDKHXHKGTGPBKQYSLPXPJCKBMLLXDZSTBKLGGQKQLSBKKTFXRMDKBFTPZFRTBBRFERQGXYJPZSSTLBZTPSZQZSJDHLJQLZBPMSMMSXLQQNHKNBLRDDNXXDHDDJCYYGYLXGZLXSYGMQQGKHBPMXYXLYTQWLWGCPBMQXCYZYDRJBHTDJYHQSHTMJSBYPLWHLZFFNYPMHXXHPLTBQPFBJWQDBYGPNZTPFZJGSDDTQSHZEAWZZYLLTYYBWJKXXGHLFKXDJTMSZSQYNZGGSWQSPHTLSSKMCLZXYSZQZXNCJDQGZDLFNYKLJCJLLZLMZZNHYDSSHTHZZLZZBBHQZWWYCRZHLYQQJBEYFXXXWHSRXWQHWPSLMSSKZTTYGYQQWRSLALHMJTQJSMXQBJJZJXZYZKXBYQXBJXSHZTSFJLXMXZXFGHKZSZGGYLCLSARJYHSLLLMZXELGLXYDJYTLFBHBPNLYZFBBHPTGJKWETZHKJJXZXXGLLJLSTGSHJJYQLQZFKCGNNDJSSZFDBCTWWSEQFHQJBSAQTGYPQLBXBMMYWXGSLZHGLZGQYFLZBYFZJFRYSFMBYZHQGFWZSYFYJJPHZBYYZFFWODGRLMFTWLBZGYCQXCDJYGZYYYYTYTYDWEGAZYHXJLZYYHLRMGRXXZCLHNELJJTJTPWJYBJJBXJJTJTEEKHWSLJPLPSFYZPQQBDLQJJTYYQLYZKDKSQJYYQZLDQTGJQYZJSUCMRYQTHTEJMFCTYHYPKMHYZWJDQFHYYXWSHCTXRLJHQXHCCYYYJLTKTTYTMXGTCJTZAYYOCZLYLBSZYWJYTSJYHBYSHFJLYGJXXTMZYYLTXXYPZLXYJZYZYYPNHMYMDYYLBLHLSYYQQLLNJJYMSOYQBZGDLYXYLCQYXTSZEGXHZGLHWBLJHEYXTWQMAKBPQCGYSHHEGQCMWYYWLJYJHYYZLLJJYLHZYHMGSLJLJXCJJYCLYCJPCPZJZJMMYLCQLNQLJQJSXYJMLSZLJQLYCMMHCFMMFPQQMFYLQMCFFQMMMMHMZNFHHJGTTHHKHSLNCHHYQDXTMMQDCYZYXYQMYQYLTDCYYYZAZZCYMZYDLZFFFMMYCQZWZZMABTBYZTDMNZZGGDFTYPCGQYTTSSFFWFDTZQSSYSTWXJHXYTSXXYLBYQHWWKXHZXWZNNZZJZJJQJCCCHYYXBZXZCYZTLLCQXYNJYCYYCYNZZQYYYEWYCZDCJYCCHYJLBTZYYCQWMPWPYMLGKDLDLGKQQBGYCHJXY";
//此处收录了375个多音字,数据来自于http://www.51window.net/page/pinyin
const oMultiDiff = {"19969":"DZ", "19975":"WM", "19988":"QJ", "20048":"YL", "20056":"SC", "20060":"NM", "20094":"QG", "20127":"QJ", "20167":"QC", "20193":"YG", "20250":"KH", "20256":"ZC", "20282":"SC", "20285":"QJG", "20291":"TD", "20314":"YD", "20340":"NE", "20375":"TD", "20389":"YJ", "20391":"CZ", "20415":"PB", "20446":"YS", "20447":"SQ", "20504":"TC", "20608":"KG", "20854":"QJ", "20857":"ZC", "20911":"PF", "20504":"TC", "20608":"KG", "20854":"QJ", "20857":"ZC", "20911":"PF", "20985":"AW", "21032":"PB", "21048":"XQ", "21049":"SC", "21089":"YS", "21119":"JC", "21242":"SB", "21273":"SC", "21305":"YP", "21306":"QO", "21330":"ZC", "21333":"SDC", "21345":"QK", "21378":"CA", "21397":"SC", "21414":"XS", "21442":"SC", "21477":"JG", "21480":"TD", "21484":"ZS", "21494":"YX", "21505":"YX", "21512":"HG", "21523":"XH", "21537":"PB", "21542":"PF", "21549":"KH", "21571":"E", "21574":"DA", "21588":"TD", "21589":"O", "21618":"ZC", "21621":"KHA", "21632":"ZJ", "21654":"KG", "21679":"LKG", "21683":"KH", "21710":"A", "21719":"YH", "21734":"WOE", "21769":"A", "21780":"WN", "21804":"XH", "21834":"A", "21899":"ZD", "21903":"RN", "21908":"WO", "21939":"ZC", "21956":"SA", "21964":"YA", "21970":"TD", "22003":"A", "22031":"JG", "22040":"XS", "22060":"ZC", "22066":"ZC", "22079":"MH", "22129":"XJ", "22179":"XA", "22237":"NJ", "22244":"TD", "22280":"JQ", "22300":"YH", "22313":"XW", "22331":"YQ", "22343":"YJ", "22351":"PH", "22395":"DC", "22412":"TD", "22484":"PB", "22500":"PB", "22534":"ZD", "22549":"DH", "22561":"PB", "22612":"TD", "22771":"KQ", "22831":"HB", "22841":"JG", "22855":"QJ", "22865":"XQ", "23013":"ML", "23081":"WM", "23487":"SX", "23558":"QJ", "23561":"YW", "23586":"YW", "23614":"YW", "23615":"SN", "23631":"PB", "23646":"ZS", "23663":"ZT", "23673":"YG", "23762":"TD", "23769":"ZS", "23780":"QJ", "23884":"QK", "24055":"XH", "24113":"DC", "24162":"ZC", "24191":"GA", "24273":"QJ", "24324":"NL", "24377":"TD", "24378":"QJ", "24439":"PF", "24554":"ZS", "24683":"TD", "24694":"WE", "24733":"LK", "24925":"TN", "25094":"ZG", "25100":"XQ", "25103":"XH", "25153":"PB", "25170":"PB", "25179":"KG", "25203":"PB", "25240":"ZS", "25282":"FB", "25303":"NA", "25324":"KG", "25341":"ZY", "25373":"WZ", "25375":"XJ", "25384":"A", "25457":"A", "25528":"SD", "25530":"SC", "25552":"TD", "25774":"ZC", "25874":"ZC", "26044":"YW", "26080":"WM", "26292":"PB", "26333":"PB", "26355":"ZY", "26366":"CZ", "26397":"ZC", "26399":"QJ", "26415":"ZS", "26451":"SB", "26526":"ZC", "26552":"JG", "26561":"TD", "26588":"JG", "26597":"CZ", "26629":"ZS", "26638":"YL", "26646":"XQ", "26653":"KG", "26657":"XJ", "26727":"HG", "26894":"ZC", "26937":"ZS", "26946":"ZC", "26999":"KJ", "27099":"KJ", "27449":"YQ", "27481":"XS", "27542":"ZS", "27663":"ZS", "27748":"TS", "27784":"SC", "27788":"ZD", "27795":"TD", "27812":"O", "27850":"PB", "27852":"MB", "27895":"SL", "27898":"PL", "27973":"QJ", "27981":"KH", "27986":"HX", "27994":"XJ", "28044":"YC", "28065":"WG", "28177":"SM", "28267":"QJ", "28291":"KH", "28337":"ZQ", "28463":"TL", "28548":"DC", "28601":"TD", "28689":"PB", "28805":"JG", "28820":"QG", "28846":"PB", "28952":"TD", "28975":"ZC", "29100":"A", "29325":"QJ", "29575":"SL", "29602":"FB", "30010":"TD", "30044":"CX", "30058":"PF", "30091":"YSP", "30111":"YN", "30229":"XJ", "30427":"SC", "30465":"SX", "30631":"YQ", "30655":"QJ", "30684":"QJG", "30707":"SD", "30729":"XH", "30796":"LG", "30917":"PB", "31074":"NM", "31085":"JZ", "31109":"SC", "31181":"ZC", "31192":"MLB", "31293":"JQ", "31400":"YX", "31584":"YJ", "31896":"ZN", "31909":"ZY", "31995":"XJ", "32321":"PF", "32327":"ZY", "32418":"HG", "32420":"XQ", "32421":"HG", "32438":"LG", "32473":"GJ", "32488":"TD", "32521":"QJ", "32527":"PB", "32562":"ZSQ", "32564":"JZ", "32735":"ZD", "32793":"PB", "33071":"PF", "33098":"XL", "33100":"YA", "33152":"PB", "33261":"CX", "33324":"BP", "33333":"TD", "33406":"YA", "33426":"WM", "33432":"PB", "33445":"JG", "33486":"ZN", "33493":"TS", "33507":"QJ", "33540":"QJ", "33544":"ZC", "33564":"XQ", "33617":"YT", "33632":"QJ", "33636":"XH", "33637":"YX", "33694":"WG", "33705":"PF", "33728":"YW", "33882":"SR", "34067":"WM", "34074":"YW", "34121":"QJ", "34255":"ZC", "34259":"XL", "34425":"JH", "34430":"XH", "34485":"KH", "34503":"YS", "34532":"HG", "34552":"XS", "34558":"YE", "34593":"ZL", "34660":"YQ", "34892":"XH", "34928":"SC", "34999":"QJ", "35048":"PB", "35059":"SC", "35098":"ZC", "35203":"TQ", "35265":"JX", "35299":"JX", "35782":"SZ", "35828":"YS", "35830":"E", "35843":"TD", "35895":"YG", "35977":"MH", "36158":"JG", "36228":"QJ", "36426":"XQ", "36466":"DC", "36710":"JC", "36711":"ZYG", "36767":"PB", "36866":"SK", "36951":"YW", "37034":"YX", "37063":"XH", "37218":"ZC", "37325":"ZC", "38063":"PB", "38079":"TD", "38085":"QY", "38107":"DC", "38116":"TD", "38123":"YD", "38224":"HG", "38241":"XTC", "38271":"ZC", "38415":"YE", "38426":"KH", "38461":"YD", "38463":"AE", "38466":"PB", "38477":"XJ", "38518":"YT", "38551":"WK", "38585":"ZC", "38704":"XS", "38739":"LJ", "38761":"GJ", "38808":"SQ", "39048":"JG", "39049":"XJ", "39052":"HG", "39076":"CZ", "39271":"XT", "39534":"TD", "39552":"TD", "39584":"PB", "39647":"SB", "39730":"LG", "39748":"TPB", "40109":"ZQ", "40479":"ND", "40516":"HG", "40536":"HG", "40583":"QJ", "40765":"YQ", "40784":"QJ", "40840":"YK", "40863":"QJG"};
//返回值:拼音首字母串数组
function makePy(str) {
	if (typeof (str) != "string") {
		throw new Error(-1, "\u51fd\u6570makePy\u9700\u8981\u5b57\u7b26\u4e32\u7c7b\u578b\u53c2\u6570!");
	}
	var arrResult = new Array(); //保存中间结果的数组
	for (var i = 0, len = str.length; i < len; i++) {
//获得unicode码
		var ch = str.charAt(i);
//检查该unicode码是否在处理范围之内,在则返回该码对映汉字的拼音首字母,不在则调用其它函数处理
		arrResult.push(checkCh(ch));
	}
//处理arrResult,返回所有可能的拼音首字母串数组
	return mkRslt(arrResult);
}
function checkCh(ch) {
	var uni = ch.charCodeAt(0);
//如果不在汉字处理范围之内,返回原字符,也可以调用自己的处理函数
	if (uni > 40869 || uni < 19968) {
		return ch;
	} //dealWithOthers(ch);
//检查是否是多音字,是按多音字处理,不是就直接在strChineseFirstPY字符串中找对应的首字母
	return (oMultiDiff[uni] ? oMultiDiff[uni] : (strChineseFirstPY.charAt(uni - 19968)));
}
function mkRslt(arr) {
	var arrRslt = [""];
	for (var i = 0, len = arr.length; i < len; i++) {
		var str = arr[i];
		var strlen = str.length;
		if (strlen == 1) {
			for (var k = 0; k < arrRslt.length; k++) {
				arrRslt[k] += str;
			}
		} else {
			var tmpArr = arrRslt.slice(0);
			arrRslt = [];
			for (k = 0; k < strlen; k++) {
//复制一个相同的arrRslt
				var tmp = tmpArr.slice(0);
//把当前字符str[k]添加到每个元素末尾
				for (var j = 0; j < tmp.length; j++) {
					tmp[j] += str.charAt(k);
				}
//把复制并修改后的数组连接到arrRslt上
				arrRslt = arrRslt.concat(tmp);
			}
		}
	}
	return arrRslt;
}
//两端去空格函数
String.prototype.trim = function () {
	return this.replace(/(^\s*)|(\s*$)/g, "");
};
export default{
    name:"Content",
    data () {
        return {
            childIds:[],
            writeable:1,
            childeProps:{
                nodeName:"",
                nodeType:"",
                templateType:[]
            },
            mountDefine:{
                mountVal:'/',
                mountData:'',
                mountDatas:[

                ],
                mountAdd:'',
            },
            
            showMenu:false,
            showMount:true,
            activeTabIndex:0,
            structDefine:{
                columnPros:{
                    columnId:"",
                    columnName:"",
                    abcName:"",
                    columnLength:10,
                    columnType:"char",
                    sortType:0,
                    sortLevel:0,
                },
                currentTempletNode:{

                },
                columnTypeOptions:[
                    {value:"char",label:"字符型"},
                    {value:"int",label:"整型"},
                    {value:"float",label:"浮点型"},
                    {value:"date",label:"日期"},
                ],
                selectGroup:[],
                updateColumnDialogVisible:false,                
                addColumnDialogVisible:false,
                columns:[
                    {width: 30, titleAlign: 'center',columnAlign:'center',type: 'selection',isResize:true},
                    {field: 'columnName', title:'字段名称', width: 50, titleAlign: 'center',columnAlign:'center',isResize:true},
                    {field: 'abcName', title:'字段代码', width: 20, titleAlign: 'center',columnAlign:'center',isResize:true},
                    {field: 'columnType', title:'字段类型', width: 20, titleAlign: 'center',columnAlign:'center',isResize:true},
                    {field: 'columnLength', title:'字段长度', width: 10, titleAlign: 'center',columnAlign:'center',isResize:true},
                    {field: 'sortInfo', title:'排序类型', width: 10, titleAlign: 'center',columnAlign:'center',isResize:true},
                    {field: 'sortLevel', title:'排序优先级', width: 10, titleAlign: 'center',columnAlign:'center',isResize:true},
                ],
                tableData:[
                    
                     
                ],
            },
            sortDefine:{
                data:[
                    {id:"1",columnName:'全宗号',sortLevel:0,sortType:0},
                    {id:"2",columnName:'全宗号',sortLevel:3,sortType:1},
                    {id:"3",columnName:'全宗号',sortLevel:4,sortType:-1},
                    {id:"4",columnName:'全宗号',sortLevel:0,sortType:0},
                    {id:"5",columnName:'全宗号',sortLevel:0,sortType:0},
                    {id:"6",columnName:'全宗号',sortLevel:2,sortType:1},
                    {id:"7",columnName:'全宗号',sortLevel:1,sortType:-1},

                ]
            },
            addTreeNodeDialogVisible:false,
            
            znodeData: [
                    
            ],
            setting:{
                view: {
                    showLine: true,
                    txtSelectedEnable: false,
                },
                data: {
                    key:{
                        name:"nodeName"
                    },
                    simpleData: {
                        enable:true,
                        idKey: "id",
                        pIdKey: "parentNodeId",
                        rootPId: undefined
                    },
                    
                },
                callback: {
                    onClick: (event,treeId,treeNode)=>{

                        this.mountDefine.mountData='';
                        console.log(this.mountDefine.mountData)
                        
                        console.log(treeNode);
                        
                        if((treeNode.writeable==undefined)||(treeNode.writeable==0)){
                            this.operation('warning','您没有该节点的权限，详情请咨询管理员');
                            this.showMenu=false;
                        }else{
                            if(treeNode.templetType==undefined){
                                this.showMenu=false;
                            }else{

                                if(treeNode.templetName.indexOf('案卷级')!=-1){
                                    this.showMount=false;
                                }else{
                                    this.showMount=true;
                                }
                                
                                this.structDefine.currentTempletNode=treeNode;
                                this.$axios.post(
                                    '/api/api/archives/column/select',
                                    {
                                        templetId:treeNode.id
                                    }
                                ).then((res)=>{
                                    console.log("列数据",res);
                                    //处理服务器返回的列数据
                                    res.data.columns.map(item=>{
                                        
                                        switch(item.sortType){
                                            case 0:item.sortInfo="不参与排序";break;
                                            case -1:item.sortInfo="降序";break;
                                            case 1:item.sortInfo="升序";break;
                                            default:break;
                                        }
                                        return item;
                                    })
                                    this.structDefine.tableData=res.data.columns;
                                    console.log(this.structDefine.tableData);
                                    let arr='';
                                    for(var i=0;i<this.structDefine.tableData.length;i++){
                                        arr=arr+this.structDefine.tableData[i].abcName
                                    }
                                    console.log(treeNode.pathRule)
                                    
                                
                                    if(treeNode.pathRule!=undefined){
                                        let path=JSON.parse(treeNode.pathRule);
                                        for(var i=0;i<path.length;i++){
                                            if(arr.indexOf(path[i])!=-1){
                                                for(var j=0;j<this.structDefine.tableData.length;j++){
                                                    if(path[i]==this.structDefine.tableData[j].abcName){
                                                        this.mountDefine.mountData+=this.structDefine.tableData[j].columnName;
                                                    }
                                                }
                                            }else{
                                                this.mountDefine.mountData+=path[i];
                                            }
                                        }
                                    
                                    this.mountDefine.mountDatas=[].concat(path); 
                                    this.showMenu=true;
                                    }else{
                                        this.showMenu=true;
                                    }
                                                                
                                    
                                }).catch((err)=>{

                                })
                                

                            }
                        }
                        
                         
                        
                    },
                    onNodeCreated:(event, treeId, treeNode)=>{
                       
                    }
                }
            }
        }
    },
    props: ["treeShow"],
    created(){
        
    },
    mounted(){
        var writeableList=JSON.parse(window.sessionStorage.getItem('writeable'))
        this.znodeData=[];
        var self=this;
        this.$axios.get(
            '/api/api/templetTree/node/selectAll',
            ).then(function(res){
                console.log(res);
                
                
                console.log(res.data.templetNodes[1]);
                for(var i=0;i<res.data.templetNodes.length;i++){
                    res.data.templetNodes[i].nodeName=res.data.templetNodes[i].templetName;
                    res.data.templetNodes[i].parentNodeId=res.data.templetNodes[i].parentId;
                    res.data.templetNodes[i].icon = './static/icon/moban.png';
                    res.data.templetNodes[i].writeable=1;
                    for(var k=0;k<writeableList.length;k++){
                        if(writeableList[k].templetTreeId==res.data.templetNodes[i].id){
                            res.data.templetNodes[i].writeable=writeableList[k].writeable
                        }
                    }
                        
                    

                }
                
                for(var j=0;j<res.data.nodes.length;j++){
                    res.data.nodes[j].writeable=1;
                    for(var l=0;l<writeableList.length;l++){
                        if(writeableList[l].templetTreeId==res.data.nodes[j].id){
                            res.data.nodes[j].writeable=writeableList[l].writeable
                        }
                    }
                    //res.data.nodes[0].writeable=1;
                    //res.data.nodes[6].writeable=true;
                    
                    if((res.data.nodes[j].nodeType!=6)&&(res.data.nodes[j].nodeType!=5)){
                        console.log(res.data.nodes[j])
                        switch(res.data.nodes[j].nodeType){
                            case 0:res.data.nodes[j].icon = './static/icon/quanzong.png';break;
                            case 1:res.data.nodes[j].icon = './static/icon/fenlei.png';break;
                            case 2:res.data.nodes[j].icon = './static/icon/hezi.png';break;
                            case 3:res.data.nodes[j].icon = './static/icon/hezi.png';break;
                            case 4:res.data.nodes[j].icon = './static/icon/hezi.png';break;
                            
                            default: break;
                        }

                        
                        self.znodeData.push(res.data.nodes[j])

                    }

                }
                self.znodeData=self.znodeData.concat(res.data.templetNodes);
                console.log(self.znodeData);
                $.fn.zTree.init($("#templeteTree"), self.setting, self.znodeData);
                var treeObj = $.fn.zTree.getZTreeObj("templeteTree");
                var nodes = treeObj.getNodesByParam("writeable", 0, null);
                console.log(nodes)
                for(var x=0;x<nodes.length;x++){
                    self.findParentNodes(nodes[x].id)
                }
                
            }).catch(function(err){
                console.log(err)
            })
        
    },
    methods: {
        
        operation(status,text){
            var self=this;  
            self.$message({
                type: status,
                message: text
            })
            
            
        },
        //遍历找孩子节点
        findParentNodes(id){
            
            var treeObj = $.fn.zTree.getZTreeObj("templeteTree");
            var nodes = treeObj.getNodesByParam("id", id, null);
            if((nodes.length==1)&&(nodes[0].children!=undefined)){
                var childNodes= nodes[0].children
                for(var y=0;y<childNodes.length;y++){
                    childNodes[y].writeable=0;
                    this.findParentNodes(childNodes[y].id)
                }
            }
            
        },
        showAddTreeNodeDialog(){
            var tree = $.fn.zTree.getZTreeObj("templeteTree");
            var selectedNode = tree.getSelectedNodes();
            console.log(selectedNode)
            if(selectedNode.length==0){
                console.log('null')
                this.addTreeNodeDialogVisible=false;
                this.$alert('请先选中节点', '提示', {
                    confirmButtonText: '确定', 
                    callback:action=>{

                    }         
                });
            }else if((selectedNode[0].templetType!=null)||(selectedNode[0].nodeType==2)||(selectedNode[0].nodeType==3)||(selectedNode[0].nodeType==4)){
                this.addTreeNodeDialogVisible=false;
                this.$alert('该节点无法增加节点，请重新选择', '提示', {
                    confirmButtonText: '确定', 
                    callback:action=>{

                    }         
                });
            }else{
                if((selectedNode[0].writeable==undefined)||(selectedNode[0].writeable==0)){
                    this.operation('warning','您没有该节点的权限，详情请咨询管理员');
                }else{
                    console.log('yes')
                    this.addTreeNodeDialogVisible=true;
                }
  
            }
        },
        
        addChildNode(){
            if(this.childeProps.nodeName==''||this.childeProps.nodeType==''){
                this.operation('error','操作有误，数据不全');
            }else{
            var tree = $.fn.zTree.getZTreeObj("templeteTree");
            var selectedNode = tree.getSelectedNodes()[0];
            var self=this;
            if(self.childeProps.nodeType==1){
                self.$axios.post(
                    "/api/api/templetTree/directoryNode/add",
                    {
                        "nodeName":self.childeProps.nodeName,
                        "parentNodeId":selectedNode.id,
                        "rootId":selectedNode.rootId,
                    }
                ).then(function(res){
                    self.$message({
                        type: 'success',
                        message: `添加成功`
                    });
                     console.log(res);
                    
                    res.data.newDirectoryNode.icon = "./static/icon/fenlei.png";
                    res.data.newDirectoryNode.writeable=1;
                    tree.addNodes(selectedNode, res.data.newDirectoryNode);
                    //tree.updateNode(selectedNode);

                }).catch(function(err){
                    console.log(err);
                })
            }else if(self.childeProps.nodeType==2){
                //案卷级和件合盒级
                if(self.childeProps.templateType.length==2){
                    self.$axios.post(
                        "/api/api/templetTree/dataNode/add",
                    {
                        "nodeName":self.childeProps.nodeName,
                        "parentNodeId":selectedNode.id,
                        "rootId":selectedNode.rootId,
                        "nodeType":4,
                    }).then(function(res){
                        self.$message({
                            type: 'success',
                            message: `添加成功`
                        });
                        console.log(res);
                        self.$axios.post(
                            '/api/api/templetTree/node/getTempletsByParentId',
                            {
                                nodeId:res.data.newNode.id
                            }
                        ).then(function(res1){
                            console.log(res1);
                            
                            res.data.newNode.icon = "./static/icon/hezi.png";  
                            res.data.newNode.writeable=1;
                            tree.addNodes(selectedNode, res.data.newNode);
                            var parentNode=tree.getNodesByParam('id',res.data.newNode.id,null)[0];
                            for(var i=0;i<res1.data.templets.length;i++){
                                res1.data.templets[i].nodeName=res1.data.templets[i].templetName;
                                res1.data.templets[i].parentNodeId=res1.data.templets[i].parentId;
                                res1.data.templets[i].icon= "./static/icon/moban.png";
                                res1.data.templets[i].writeable=1;
                                tree.addNodes(parentNode,res1.data.templets[i]);
                            }
                        }).catch(function(err){
                            console.log(err);
                        })
                        
                    }).catch(function(err){
                        console.log(err);
                })
                //案卷级
                }else if(self.childeProps.templateType[0]=='案卷级'){
                    self.$axios.post(
                        "/api/api/templetTree/dataNode/add",
                    {
                        "nodeName":self.childeProps.nodeName,
                        "parentNodeId":selectedNode.id,
                        "rootId":selectedNode.rootId,
                        "nodeType":3
                    }).then(function(res){
                        self.$message({
                            type: 'success',
                            message: `添加成功`
                        });
                        console.log(res);
                        console.log('123');
                        self.$axios.post(
                            '/api/api/templetTree/node/getTempletsByParentId',
                            {
                                'nodeId':res.data.newNode.id
                            }).then(function(res1){
                                res.data.newNode.icon = "./static/icon/hezi.png";
                                res.data.newNode.writeable=1;
                                tree.addNodes(selectedNode, res.data.newNode);
                                console.log(res1);
                                var parentNode = tree.getNodesByParam("id", res.data.newNode.id, null)[0];
                                // console.log(res.data.nodeId);

                                // console.log('parentNode',parentNode);
                                for(var i=0;i<res1.data.templets.length;i++){
                                    res1.data.templets[i].nodeName=res1.data.templets[i].templetName;
                                    res1.data.templets[i].parentNodeId=res1.data.templets[i].parentId;
                                    res1.data.templets[i].icon = "./static/icon/moban.png";
                                    res1.data.templets[i].writeable=1;
                                    console.log(res1.data.templets[i])
                                    tree.addNodes(parentNode, res1.data.templets[i]);
                                }
                                

                            }).catch(function(err){
                                console.log(err);
                            })
                            
                    }).catch(function(err){
                        console.log(err);
                })
                //件盒级
                }else if(self.childeProps.templateType[0]=='件盒级'){
                    self.$axios.post(
                        "/api/api/templetTree/dataNode/add",
                    {
                        "nodeName":self.childeProps.nodeName,
                        "parentNodeId":selectedNode.id,
                        "rootId":selectedNode.rootId,
                        "nodeType":2
                    }).then(function(res){
                        self.$message({
                            type: 'success',
                            message: `添加成功`
                        });
                        console.log(res);
                        self.$axios.post(
                            '/api/api/templetTree/node/getTempletsByParentId',
                            {
                                'nodeId':res.data.newNode.id
                            }
                        ).then(function(res1){
                            console.log(res1);
                            res.data.newNode.icon = "./static/icon/hezi.png"; 
                            res.data.newNode.writeable=1;
                            tree.addNodes(selectedNode,res.data.newNode);
                            var parentNode=tree.getNodesByParam("id", res.data.newNode.id, null)[0];
                            res1.data.templets[0].nodeName=res1.data.templets[0].templetName;
                            res1.data.templets[0].parentNodeId=res1.data.templets[0].parentId;
                            res1.data.templets[0].icon = "./static/icon/moban.png";
                            res1.data.templets[0].writeable=1;
                            tree.addNodes(parentNode,res1.data.templets);
                        }).catch(function(err){
                            console.log(err);
                        })
                        
                    }).catch(function(err){
                        console.log(err);
                })
                }else if(self.childeProps.templateType.length==0){
                    this.operation('warning','请选择模板类型');
                }


                
                
            }
            
            
            //向后台发起请求，添加子节点
            }
            
        },
        //删除节点
        deleteTreeNode(){
            var self=this;
            var tree = $.fn.zTree.getZTreeObj("templeteTree");
            var selectedNode = tree.getSelectedNodes();
            if(selectedNode.length==0){
                
                this.$alert('请先选中要删除节点', '提示', {
                    confirmButtonText: '确定',
                    callback: action => {
                        // this.$message({
                        // type: 'info',
                        // message:" "
                        // });
                    }       
                });
            }else if(selectedNode.length>1){
                // this.addTreeNodeDialogVisible=false;
                this.$alert('一次只能删除一个节点', '安全提示', {
                    confirmButtonText: '确定', 
                    callback:action=>{

                    }      
                });
            }else{
                if((selectedNode[0].writeable==undefined)||(selectedNode[0].writeable==0)){
                    self.operation('warning','您没有该节点的权限，详情请咨询管理员')
                }else{
                    if(selectedNode[0].nodeType==0){
                    // this.addTreeNodeDialogVisible=false;
                        this.$alert('请在系统设置中删除全宗节点', '安全提示', {
                            confirmButtonText: '确定',      
                            callback:action=>{

                            } 
                        });
                    }else{
                        if(selectedNode[0].templetType!=undefined){
                            // this.addTreeNodeDialogVisible=false;
                            this.$alert('无法直接删除模板节点，如想删除，请删除上一级，谨慎删除！', '安全提示', {
                                confirmButtonText: '确定',
                                callback:action=>{

                                }       
                            });
                        }
                        else{
                            this.$confirm('此操作将永久删除该节点, 是否继续?', '提示', {
                                confirmButtonText: '确定',
                                cancelButtonText: '取消',
                                type: 'warning'
                            }).then(() => {       
                                self.$axios.post(
                                    '/api/api/templetTree/node/delete',
                                    {
                                        id:selectedNode[0].id
                                    }
                                ).then(res=>{
                                    console.log(res);
                                    if(res.data.success==1){
                                        tree.removeNode(selectedNode[0]);
                                        this.$message({
                                            type: 'success',
                                            message: '删除成功!'
                                        });
                                    }else{
                                        this.$message({
                                            type: 'error',
                                            message: '删除失败!'
                                        });
                                    }
                                    
                                }).catch(err=>{
                                    console.log(err);

                                })
                                
                            }).catch(() => {
                                this.$message({
                                    type: 'info',
                                    message: '已取消删除'
                                });          
                            });
                        }
                        
                    }
                }
                
                
            }
            
        },
        //弹出框关闭
        handleClose(done){
            if(this.structDefine.updateColumnDialogVisible == true){
                this.structDefine.updateColumnDialogVisible = false;
            }
            if(this.structDefine.addColumnDialogVisible == true){
                this.structDefine.addColumnDialogVisible = false;
            }
            if(this.addTreeNodeDialogVisible==true){
                this.structDefine.addColumnDialogVisible = false;
            }
            done();
            
        },
        selectChange(selection,rowData){
            console.log('select-change',selection,rowData);
            this.structDefine.selectGroup = selection;
        },
        rowClick(rowIndex,rowData,column){
            //console.log(column._checked);

        },
        // selectGroupChange(selection){
        //     console.log("selectGroupChange");
        //     this.structDefine.columnPros.columnId = selection[0].id;
        //     this.structDefine.columnPros.columnName = selection[0].columnName;
        //     this.structDefine.columnPros.abcName = selection[0].abcName;
        //     this.structDefine.columnPros.columnType = selection[0].columnType;
        //     this.structDefine.columnPros.columnLength = selection[0].columnLength;
        // },
        checkedCurrentRow(e){
            console.log(e.target)
        },
        checkedChange(index){
            console.log("点击的复选框索引为"+index);
            var currentRow = this.sortDefine.data[index];
            //如果排序方式（为升序或降序），即不为0
            if(currentRow.sortType != 0){
                //将排序级别在该字段之后的排序级别重新设置，即减1
                this.dropSortLevel(currentRow.sortLevel)
                // //设置字段排序级别为0，即不参与排序
                // currentRow.sortLevel = 0;
                // //将排序方式设为0
                // currentRow.sortType = 0;

            }else{
                //如果还没参与排序，设置默认的排序方式为升序
                currentRow.sortType = 1;
                //将该字段的排序级别设为最后一个
                currentRow.sortLevel = this.addSortLevel();
            }
            
        },
        mountAddClick(index){
            if(index==-1){
                this.mountDefine.mountData+=this.mountDefine.mountVal;
                this.mountDefine.mountDatas.push(this.mountDefine.mountVal);
            }else{
                this.mountDefine.mountData+=this.structDefine.tableData[index].columnName;
                this.mountDefine.mountDatas.push(this.structDefine.tableData[index].abcName);
                
                console.log(this.mountDefine.mountData);
                console.log(this.mountDefine.mountDatas);
            }
            
        },
        dropSortLevel(sortLevel){
            console.log("将索引为"+sortLevel+"的")
            var newData = this.sortDefine.data.map((item)=>{
                if(item.sortLevel == sortLevel){
                    item.sortLevel = 0;
                    item.sortType = 0;
                    return item;
                }else if(item.sortLevel > sortLevel){
                    item.sortLevel--; 
                    return item;
                }else{
                    return item;
                }
            })
            console.log(newData);
        },
        addMountData(){
            var tree = $.fn.zTree.getZTreeObj("templeteTree");
            var selectedNode = tree.getSelectedNodes()[0];
            this.$axios.post(
                '/api/api/templetTree/templet/setPathRule',
                {
                    id:selectedNode.id,
                    pathRule:this.mountDefine.mountDatas
                }
            ).then(
                (res)=>{
                    console.log(res)
                    if(res.data.success==1){
                        selectedNode.pathRule=JSON.stringify(this.mountDefine.mountDatas)
                        tree.updateNode(selectedNode);
                        this.operation('success','设置成功')
                    }
                }
            ).catch(
                (err)=>{
                    console.log(err)
                }
            )
        },
        unaddMountData(){
            this.mountDefine.mountDatas=[];
            this.mountDefine.mountData='';
        },
        addSortLevel(){
            var newData = this.sortDefine.data.filter((item)=>{
                return item.sortLevel != 0;
            });
            return newData.length+1;
        },
        changSortType(index){
            if(this.sortDefine.data[index].sortType == 0)
                this.dropSortLevel(this.sortDefine.data[index].sortLevel);
            console.log(this.sortDefine.data[index].sortType);
        },
        commitSortRules(){
            //异步请求提交排序设置
        },
        getPY(hanzi){
            return makePy(hanzi)[0];
        },
        addColumn(){
                //异步提交column数据
            this.$axios.post(
                '/api/api/archives/column/add',
                {
                    
                    columnName:this.structDefine.columnPros.columnName,
                    abcName:this.structDefine.columnPros.abcName,
                    columnType:this.structDefine.columnPros.columnType,
                    columnLength:this.structDefine.columnPros.columnLength,
                    sortType:this.structDefine.columnPros.sortType,
                    templetId:this.structDefine.currentTempletNode.id,
                    sortLevel:this.structDefine.columnPros.sortLevel
                }
            ).then(
                (res)=>{
                    console.log(res);
                    
                    if(res.data.newColumn.sortType == 0){
                        res.data.newColumn.sortInfo="不参与排序"
                    }else if(res.data.newColumn.sortType == 1){
                        res.data.newColumn.sortInfo="升序"
                    }else if(res.data.newColumn.sortType == -1){
                        res.data.newColumn.sortInfo="降序"
                    }
                    this.structDefine.tableData.push(
                        res.data.newColumn
                    );
                    this.operation('success','添加成功');
                }
            ).catch(
                (err)=>{
                    console.log(err);
                }
            ) 
        },
        showUpdateColumnDialog(){

            //this.structDefine.columnPros = 
        },
        updateColumn(){
            var tree = $.fn.zTree.getZTreeObj("templeteTree");
            var selectedNode = tree.getSelectedNodes()[0];
            console.log("修改的列数据：",this.structDefine.columnPros);
            this.$axios.post(
                '/api/api/archives/column/update',
                {
                    id:this.structDefine.selectGroup[0].id,
                    columnName:this.structDefine.columnPros.columnName,
                    abcName:this.structDefine.columnPros.abcName,
                    columnType:this.structDefine.columnPros.columnType,
                    columnLength:this.structDefine.columnPros.columnLength,
                    sortType:this.structDefine.columnPros.sortType,
                    templetId:this.structDefine.currentTempletNode.id,
                    sortLevel:this.structDefine.columnPros.sortLevel,
                }
            ).then(
                (res)=>{
                    console.log(res);
                    
                    this.$axios.post(
                        '/api/api/archives/column/select',
                        {
                            templetId:selectedNode.id
                        }
                    ).then((res)=>{
                        console.log(res);     
                        this.operation('success','修改成功');
                        res.data.columns.map(item=>{
                            switch(item.sortType){
                                case 0:item.sortInfo="不参与排序";break;
                                    case -1:item.sortInfo="降序";break;
                                    case 1:item.sortInfo="升序";break;
                                default:break;
                            }
                            return item;
                        })   
                        this.structDefine.tableData=res.data.columns;
                        this.structDefine.selectGroup=[];
                        
                        
                    }).catch((err)=>{

                    })
                }
            ).catch(
                (err)=>{
                    console.log(err);
                }
            )

        },
        deleteColumn(){
            if(this.structDefine.selectGroup.length==0){
                this.operation('error','请选择至少一个字段');
            }else{
                var tree = $.fn.zTree.getZTreeObj("templeteTree");
                var selectedNode = tree.getSelectedNodes()[0];
                for(var i=0;i<this.structDefine.selectGroup.length;i++){
                    this.$axios.post(
                        '/api/api/archives/column/delete',
                        {
                            id:this.structDefine.selectGroup[i].id
                        }
                    ).then(
                        (res)=>{
                            console.log(res)
                            this.$axios.post(
                            '/api/api/archives/column/select',
                            {
                                templetId:selectedNode.id
                            }
                        ).then((res1)=>{
                            console.log(res1);     
                            this.operation('success','成功删除'+i+'条');   
                            this.structDefine.tableData=res1.data.columns;
                            this.structDefine.selectGroup=[];
                            
                        }).catch((err)=>{

                        })
                        }
                    ).catch(
                        (err)=>{
                            console.log(err)
                        }
                    )
                }
            }          
        },
        backDeskClick(){
            this.$router.push({path:"/"});
        }
        // zTreeOnClick(event,treeId,treeNode){
        //     console.log(treeNode)
        // }
    },
    watch:{
        'structDefine.selectGroup':function(selection,oldSelection){
            if(selection.length > 0){
                this.structDefine.columnPros.columnId = selection[0].id;
                this.structDefine.columnPros.columnName = selection[0].columnName;
                this.structDefine.columnPros.abcName = selection[0].abcName;
                this.structDefine.columnPros.columnType = selection[0].columnType;
                this.structDefine.columnPros.columnLength = selection[0].columnLength;
                this.structDefine.columnPros.sortType = selection[0].sortType;
                this.structDefine.columnPros.sortLevel = selection[0].sortLevel;
            }
        }
    }
}
</script>

<style scoped>
#tools-bar{
    padding:5px 30px;
}
#mainWrapper{
    flex-grow: 1;
    height: 100%;;
    display: flex;
    flex-direction: column;
}
.line{
    height: 1px;
    background-color: darkgrey;
}
.close-btn{
    float: right;
}
.title{
    font-size: 25px;

}
#tool-bar el-button-group{
    margin-left: 50px;
}
#mainContent{
    flex-grow: 1;
    width: 100%;
    height: auto;
    display:  flex;
    flex-direction: row;
}
#treeWrapper{
    width: 289px;
    border-right: darkgrey  solid 1px;
    overflow:auto;

}
#workSpace{
    flex-grow: 1;
    display: flex;
    flex-direction: column;
    
}

.tab-menu{

    display: flex;
    background-color:rgb(245, 247, 250);
    height: 50px;
    
}
.tab-menu-item{
    width: 100px;
    height: 50px;
    line-height: 50px;
    text-align: center;
    color: rgb(144, 147, 153);
}
.tab-menu-item:hover{
    color: rgb(64, 170, 255);
    cursor: pointer;
}
.tab-content{
    flex-grow: 1;
    padding: 10px;
    height: 100%;
    display: flex;
    flex-direction: column;
}
.tab-active{
    background-color: white;
    color: rgb(64, 170, 255);
}
.sort-container{
    flex-grow: 1;
    overflow: auto;
}

.sort-container li{
    list-style: none;
    display: flex;
    height: 30px;
    line-height: 30px;
    border-top: rgb(243, 243, 243) solid 1px;
    border-bottom: rgb(243, 243, 243) solid 1px;
    margin-top: 5px;

}
.mountContent{
    margin-top:10px;
    display: flex;
    flex-direction: row;
    /* background-color: aqua; */
    /* background-color: beige; */
    height: 500px;
}
.mountLi{
    
    width: 200px;
    
    background-color: beige;
    overflow:auto;
}
.mountAdd{
    width: 200px;
    height: 100%;
    line-height: 500px;
    background-color: white;
    text-align: center;
}
.mountData{
    width: 100%;
    height: 15%;
    background-color: beige;
    overflow:auto;
}
.mount-container li{
    height: 30px;
    list-style: none;
    line-height: 30px;
    
}
.sort-container li .column-name-container{
    display: block;
    width: 200px;
    text-align: center;


}
.sort-container .sort-level-container{
    display: block;
    width: 100px;
    text-align: center;
    
}

 
</style>

