<template>
    <div style="overflow:auto;flex-grow:1;">
        
        
        <div style="text-align:center;margin-top:150px">
            <h2>档案检索</h2> 
        </div>
        <div style="text-align:center;margin-top:15px">
            <el-cascader
                :options="options"
                change-on-select
                expand-trigger="hover"
                style="width:200px"
                size="small"
                :props="props"
                @change="handleChange"
                placeholder="请选择搜索范围"

            >
            </el-cascader>
            <el-input placeholder="请输入搜索字段" v-model="bigData.column" class="input-with-select" style="width:10%"></el-input>
            <el-input placeholder="请输入关键字" v-model="bigData.keyword" class="input-with-select" style="width:40%">
                <el-button slot="append" @click="handleClick" icon="el-icon-search">
                </el-button> 
            </el-input>
        </div>
        <div style="width:60%;margin:50px auto;background:red;">
            <el-table
                :data="tableData"
                height="500"
                style="width:100%">
                <el-table-column
                    prop="DH"
                    label="档号"
                    width="200">
                </el-table-column>
                <el-table-column
                    prop="value"
                    :label="bigData.column"
                    width="400">
                </el-table-column>
                <el-table-column
                    prop="tablePath"
                    label="归档位置"
                    width="400">
                </el-table-column>
                <el-table-column label="操作">
                    <template slot-scope="scope">
                        <el-button
                        size="mini"
                        @click="showDetial(scope.$index, scope.row)">详细信息</el-button>
                    </template>
                </el-table-column>
            </el-table>
        </div>
        <el-dialog title="详细信息" :visible.sync="bigData.dataListShow" width="80%" v-if="bigData.dataListShow">
            <div>
                
                <div >
                    <v-table 
                        v-loading="bigData.dataList.loading"
                        style="width:100%;"
                        :height="100"
                        :column-width-drag="true"
                        :is-vertical-resize="true"
                        odd-bg-color="#FCFCFC"
                        even-bg-color="	#FDF5E6"
                        :is-horizontal-resize="true"
                        :title-row-height="30"
                        :row-height="20"
                        title-bg-color="#87CEEB"
                        row-hover-color="#1E90FF"
                        row-click-color="#1E90FF"
                        :columns="bigData.dataList.columnsDatas"
                        :table-data="bigData.dataList.tableDatas"
                        :row-click="rowWjClick"
                    ></v-table>
                </div>
                
            </div>
            
            <span slot="footer" class="dialog-footer">
                <!-- <label>点击已挂接原文（文件数量为1）的条目，即可使用原文查看</label> -->
                <el-select v-model="value2" placeholder="查看原文">
                    <el-option
                    v-for="item in options2"
                    :key="item.value"
                    :label="item.label"
                    :value="item.value"
                    :disabled="item.disabled">
                    </el-option>
                </el-select>
                <!-- <el-button type="primary" :disabled="canShowData" @click="showData">原文查看</el-button> -->
                <el-button @click="bigData.dataListShow=false">取 消</el-button>
            </span>
        </el-dialog>
        <el-dialog title="详细信息" :visible.sync="bigData.AjdataListShow" width="80%" v-if="bigData.AjdataListShow">
            <div>
                
                <div >
                    <v-table 
                        v-loading="bigData.dataList.loading"
                        style="width:100%;"
                        :height="100"
                        :column-width-drag="true"
                        :is-vertical-resize="true"
                        odd-bg-color="#FCFCFC"
                        even-bg-color="	#FDF5E6"
                        :is-horizontal-resize="true"
                        :title-row-height="30"
                        :row-height="20"
                        title-bg-color="#87CEEB"
                        row-hover-color="#1E90FF"
                        row-click-color="#1E90FF"
                        :columns="bigData.dataList.columnsDatas"
                        :table-data="bigData.dataList.tableDatas"
                        :row-click="rowClick"
                        
                    ></v-table>
                    <v-table 
                        v-loading="bigData.dataList.loading"
                        style="width:100%;"
                        :column-width-drag="true"
                        :is-vertical-resize="true"
                        odd-bg-color="#FCFCFC"
                        even-bg-color="	#FDF5E6"
                        :is-horizontal-resize="true"
                        :title-row-height="30"
                        :row-height="20"
                        title-bg-color="#87CEEB"
                        row-hover-color="#1E90FF"
                        row-click-color="#1E90FF"
                        :columns="bigData.dataList.columnsAjDatas"
                        :table-data="bigData.dataList.tableAjDatas"
                        :row-click="rowWjClick"
                        
                    ></v-table>
                </div>
                
            </div>
            
            <span slot="footer" class="dialog-footer">
                <el-select v-model="value2" placeholder="查看原文">
                    <el-option
                    v-for="item in options2"
                    :key="item.value"
                    :label="item.label"
                    :value="item.value"
                    :disabled="item.disabled">
                    </el-option>
                </el-select>
                <el-button type="primary" :disabled="canShowData" @click="showData">原文查看</el-button>
                <el-button @click="bigData.AjdataListShow=false">取 消</el-button>
            </span>
        </el-dialog>
        <el-dialog title="原文查看" :visible.sync="dialogTableVisible" :before-close="beforeDialogTableVisible">
            <el-table 
                :data="bigdatas.fileList"
                height="250"
                border
                stripe
                style="width: 100%">
                <el-table-column property="fileName" label="文件名" width="500"></el-table-column>
                <el-table-column property="filePath" label="路径" width="300" v-if="false"></el-table-column>
                <el-table-column label="操作" >
                    <template slot-scope="scope">
                        <el-button
                        @click.native.prevent="showData(scope.$index, bigdatas.fileList)"
                        type="text"
                        size="small">
                        查看
                        </el-button>
                        <el-button
                        @click.native.prevent="downloadData(scope.$index, bigdatas.fileList)"
                        type="text"
                        size="small">
                        下载
                        </el-button>
                    </template>
                </el-table-column>
            </el-table>
        </el-dialog>
        <el-dialog title="视频文件预览" :visible.sync="showVideo" :before-close="showVideoClose" align="center" >
            <div>
                
                    <el-button style="float:left" icon="el-icon-arrow-left" @click='lastVid'>上一页</el-button>
                    
                    <el-button style="float:right" @click='nextVid'>下一页<i class="el-icon-arrow-right el-icon--right"></i></el-button>
                
            </div>
            <div>
                <h4>{{videoName}}</h4>
            </div>
            <video height="400px" :src="videoSrc" controls style="margin:0px auto"></video>
        </el-dialog>
        <el-dialog title="音频文件预览" :visible.sync="showAudio" :before-close="showAudioClose" align="center">
            <div>
                
                    <el-button style="float:left" icon="el-icon-arrow-left" @click='lastAudio'>上一页</el-button>
                    
                    <el-button style="float:right" @click='nextAudio'>下一页<i class="el-icon-arrow-right el-icon--right"></i></el-button>
                
            </div>
            <div>
                <h4>{{audioName}}</h4>
            </div>
            <audio height="400px" :src="audioSrc" controls="controls"></audio>
        </el-dialog>
        <el-dialog title="图片文件预览" :visible.sync="showPicture" :before-close="showPictureClose" align="center" v-loading="picloading">
            <div>
                
                    <el-button style="float:left" icon="el-icon-arrow-left" @click='lastPic'>上一页</el-button>
                    
                    <el-button style="float:right" @click='nextPic'>下一页<i class="el-icon-arrow-right el-icon--right"></i></el-button>
                
            </div>
            <div>
                <h4>{{picName}}</h4>
            </div>
            
            <div style="margin-top:15px">
                <img width="400px"  :src="pictureSrc" controls style="margin:0px auto" @load='onloadeddata' >
            </div>
            
            
        </el-dialog>
    </div>
</template>

<script>
const strChineseFirstPY = "YDYQSXMWZSSXJBYMGCCZQPSSQBYCDSCDQLDYLYBSSJGYZZJJFKCCLZDHWDWZJLJPFYYNWJJTMYHZWZHFLZPPQHGSCYYYNJQYXXGJHHSDSJNKKTMOMLCRXYPSNQSECCQZGGLLYJLMYZZSECYKYYHQWJSSGGYXYZYJWWKDJHYCHMYXJTLXJYQBYXZLDWRDJRWYSRLDZJPCBZJJBRCFTLECZSTZFXXZHTRQHYBDLYCZSSYMMRFMYQZPWWJJYFCRWFDFZQPYDDWYXKYJAWJFFXYPSFTZYHHYZYSWCJYXSCLCXXWZZXNBGNNXBXLZSZSBSGPYSYZDHMDZBQBZCWDZZYYTZHBTSYYBZGNTNXQYWQSKBPHHLXGYBFMJEBJHHGQTJCYSXSTKZHLYCKGLYSMZXYALMELDCCXGZYRJXSDLTYZCQKCNNJWHJTZZCQLJSTSTBNXBTYXCEQXGKWJYFLZQLYHYXSPSFXLMPBYSXXXYDJCZYLLLSJXFHJXPJBTFFYABYXBHZZBJYZLWLCZGGBTSSMDTJZXPTHYQTGLJSCQFZKJZJQNLZWLSLHDZBWJNCJZYZSQQYCQYRZCJJWYBRTWPYFTWEXCSKDZCTBZHYZZYYJXZCFFZZMJYXXSDZZOTTBZLQWFCKSZSXFYRLNYJMBDTHJXSQQCCSBXYYTSYFBXDZTGBCNSLCYZZPSAZYZZSCJCSHZQYDXLBPJLLMQXTYDZXSQJTZPXLCGLQTZWJBHCTSYJSFXYEJJTLBGXSXJMYJQQPFZASYJNTYDJXKJCDJSZCBARTDCLYJQMWNQNCLLLKBYBZZSYHQQLTWLCCXTXLLZNTYLNEWYZYXCZXXGRKRMTCNDNJTSYYSSDQDGHSDBJGHRWRQLYBGLXHLGTGXBQJDZPYJSJYJCTMRNYMGRZJCZGJMZMGXMPRYXKJNYMSGMZJYMKMFXMLDTGFBHCJHKYLPFMDXLQJJSMTQGZSJLQDLDGJYCALCMZCSDJLLNXDJFFFFJCZFMZFFPFKHKGDPSXKTACJDHHZDDCRRCFQYJKQCCWJDXHWJLYLLZGCFCQDSMLZPBJJPLSBCJGGDCKKDEZSQCCKJGCGKDJTJDLZYCXKLQSCGJCLTFPCQCZGWPJDQYZJJBYJHSJDZWGFSJGZKQCCZLLPSPKJGQJHZZLJPLGJGJJTHJJYJZCZMLZLYQBGJWMLJKXZDZNJQSYZMLJLLJKYWXMKJLHSKJGBMCLYYMKXJQLBMLLKMDXXKWYXYSLMLPSJQQJQXYXFJTJDXMXXLLCXQBSYJBGWYMBGGBCYXPJYGPEPFGDJGBHBNSQJYZJKJKHXQFGQZKFHYGKHDKLLSDJQXPQYKYBNQSXQNSZSWHBSXWHXWBZZXDMNSJBSBKBBZKLYLXGWXDRWYQZMYWSJQLCJXXJXKJEQXSCYETLZHLYYYSDZPAQYZCMTLSHTZCFYZYXYLJSDCJQAGYSLCQLYYYSHMRQQKLDXZSCSSSYDYCJYSFSJBFRSSZQSBXXPXJYSDRCKGJLGDKZJZBDKTCSYQPYHSTCLDJDHMXMCGXYZHJDDTMHLTXZXYLYMOHYJCLTYFBQQXPFBDFHHTKSQHZYYWCNXXCRWHOWGYJLEGWDQCWGFJYCSNTMYTOLBYGWQWESJPWNMLRYDZSZTXYQPZGCWXHNGPYXSHMYQJXZTDPPBFYHZHTJYFDZWKGKZBLDNTSXHQEEGZZYLZMMZYJZGXZXKHKSTXNXXWYLYAPSTHXDWHZYMPXAGKYDXBHNHXKDPJNMYHYLPMGOCSLNZHKXXLPZZLBMLSFBHHGYGYYGGBHSCYAQTYWLXTZQCEZYDQDQMMHTKLLSZHLSJZWFYHQSWSCWLQAZYNYTLSXTHAZNKZZSZZLAXXZWWCTGQQTDDYZTCCHYQZFLXPSLZYGPZSZNGLNDQTBDLXGTCTAJDKYWNSYZLJHHZZCWNYYZYWMHYCHHYXHJKZWSXHZYXLYSKQYSPSLYZWMYPPKBYGLKZHTYXAXQSYSHXASMCHKDSCRSWJPWXSGZJLWWSCHSJHSQNHCSEGNDAQTBAALZZMSSTDQJCJKTSCJAXPLGGXHHGXXZCXPDMMHLDGTYBYSJMXHMRCPXXJZCKZXSHMLQXXTTHXWZFKHCCZDYTCJYXQHLXDHYPJQXYLSYYDZOZJNYXQEZYSQYAYXWYPDGXDDXSPPYZNDLTWRHXYDXZZJHTCXMCZLHPYYYYMHZLLHNXMYLLLMDCPPXHMXDKYCYRDLTXJCHHZZXZLCCLYLNZSHZJZZLNNRLWHYQSNJHXYNTTTKYJPYCHHYEGKCTTWLGQRLGGTGTYGYHPYHYLQYQGCWYQKPYYYTTTTLHYHLLTYTTSPLKYZXGZWGPYDSSZZDQXSKCQNMJJZZBXYQMJRTFFBTKHZKBXLJJKDXJTLBWFZPPTKQTZTGPDGNTPJYFALQMKGXBDCLZFHZCLLLLADPMXDJHLCCLGYHDZFGYDDGCYYFGYDXKSSEBDHYKDKDKHNAXXYBPBYYHXZQGAFFQYJXDMLJCSQZLLPCHBSXGJYNDYBYQSPZWJLZKSDDTACTBXZDYZYPJZQSJNKKTKNJDJGYYPGTLFYQKASDNTCYHBLWDZHBBYDWJRYGKZYHEYYFJMSDTYFZJJHGCXPLXHLDWXXJKYTCYKSSSMTWCTTQZLPBSZDZWZXGZAGYKTYWXLHLSPBCLLOQMMZSSLCMBJCSZZKYDCZJGQQDSMCYTZQQLWZQZXSSFPTTFQMDDZDSHDTDWFHTDYZJYQJQKYPBDJYYXTLJHDRQXXXHAYDHRJLKLYTWHLLRLLRCXYLBWSRSZZSYMKZZHHKYHXKSMDSYDYCJPBZBSQLFCXXXNXKXWYWSDZYQOGGQMMYHCDZTTFJYYBGSTTTYBYKJDHKYXBELHTYPJQNFXFDYKZHQKZBYJTZBXHFDXKDASWTAWAJLDYJSFHBLDNNTNQJTJNCHXFJSRFWHZFMDRYJYJWZPDJKZYJYMPCYZNYNXFBYTFYFWYGDBNZZZDNYTXZEMMQBSQEHXFZMBMFLZZSRXYMJGSXWZJSPRYDJSJGXHJJGLJJYNZZJXHGXKYMLPYYYCXYTWQZSWHWLYRJLPXSLSXMFSWWKLCTNXNYNPSJSZHDZEPTXMYYWXYYSYWLXJQZQXZDCLEEELMCPJPCLWBXSQHFWWTFFJTNQJHJQDXHWLBYZNFJLALKYYJLDXHHYCSTYYWNRJYXYWTRMDRQHWQCMFJDYZMHMYYXJWMYZQZXTLMRSPWWCHAQBXYGZYPXYYRRCLMPYMGKSJSZYSRMYJSNXTPLNBAPPYPYLXYYZKYNLDZYJZCZNNLMZHHARQMPGWQTZMXXMLLHGDZXYHXKYXYCJMFFYYHJFSBSSQLXXNDYCANNMTCJCYPRRNYTYQNYYMBMSXNDLYLYSLJRLXYSXQMLLYZLZJJJKYZZCSFBZXXMSTBJGNXYZHLXNMCWSCYZYFZLXBRNNNYLBNRTGZQYSATSWRYHYJZMZDHZGZDWYBSSCSKXSYHYTXXGCQGXZZSHYXJSCRHMKKBXCZJYJYMKQHZJFNBHMQHYSNJNZYBKNQMCLGQHWLZNZSWXKHLJHYYBQLBFCDSXDLDSPFZPSKJYZWZXZDDXJSMMEGJSCSSMGCLXXKYYYLNYPWWWGYDKZJGGGZGGSYCKNJWNJPCXBJJTQTJWDSSPJXZXNZXUMELPXFSXTLLXCLJXJJLJZXCTPSWXLYDHLYQRWHSYCSQYYBYAYWJJJQFWQCQQCJQGXALDBZZYJGKGXPLTZYFXJLTPADKYQHPMATLCPDCKBMTXYBHKLENXDLEEGQDYMSAWHZMLJTWYGXLYQZLJEEYYBQQFFNLYXRDSCTGJGXYYNKLLYQKCCTLHJLQMKKZGCYYGLLLJDZGYDHZWXPYSJBZKDZGYZZHYWYFQYTYZSZYEZZLYMHJJHTSMQWYZLKYYWZCSRKQYTLTDXWCTYJKLWSQZWBDCQYNCJSRSZJLKCDCDTLZZZACQQZZDDXYPLXZBQJYLZLLLQDDZQJYJYJZYXNYYYNYJXKXDAZWYRDLJYYYRJLXLLDYXJCYWYWNQCCLDDNYYYNYCKCZHXXCCLGZQJGKWPPCQQJYSBZZXYJSQPXJPZBSBDSFNSFPZXHDWZTDWPPTFLZZBZDMYYPQJRSDZSQZSQXBDGCPZSWDWCSQZGMDHZXMWWFYBPDGPHTMJTHZSMMBGZMBZJCFZWFZBBZMQCFMBDMCJXLGPNJBBXGYHYYJGPTZGZMQBQTCGYXJXLWZKYDPDYMGCFTPFXYZTZXDZXTGKMTYBBCLBJASKYTSSQYYMSZXFJEWLXLLSZBQJJJAKLYLXLYCCTSXMCWFKKKBSXLLLLJYXTYLTJYYTDPJHNHNNKBYQNFQYYZBYYESSESSGDYHFHWTCJBSDZZTFDMXHCNJZYMQWSRYJDZJQPDQBBSTJGGFBKJBXTGQHNGWJXJGDLLTHZHHYYYYYYSXWTYYYCCBDBPYPZYCCZYJPZYWCBDLFWZCWJDXXHYHLHWZZXJTCZLCDPXUJCZZZLYXJJTXPHFXWPYWXZPTDZZBDZCYHJHMLXBQXSBYLRDTGJRRCTTTHYTCZWMXFYTWWZCWJWXJYWCSKYBZSCCTZQNHXNWXXKHKFHTSWOCCJYBCMPZZYKBNNZPBZHHZDLSYDDYTYFJPXYNGFXBYQXCBHXCPSXTYZDMKYSNXSXLHKMZXLYHDHKWHXXSSKQYHHCJYXGLHZXCSNHEKDTGZXQYPKDHEXTYKCNYMYYYPKQYYYKXZLTHJQTBYQHXBMYHSQCKWWYLLHCYYLNNEQXQWMCFBDCCMLJGGXDQKTLXKGNQCDGZJWYJJLYHHQTTTNWCHMXCXWHWSZJYDJCCDBQCDGDNYXZTHCQRXCBHZTQCBXWGQWYYBXHMBYMYQTYEXMQKYAQYRGYZSLFYKKQHYSSQYSHJGJCNXKZYCXSBXYXHYYLSTYCXQTHYSMGSCPMMGCCCCCMTZTASMGQZJHKLOSQYLSWTMXSYQKDZLJQQYPLSYCZTCQQPBBQJZCLPKHQZYYXXDTDDTSJCXFFLLCHQXMJLWCJCXTSPYCXNDTJSHJWXDQQJSKXYAMYLSJHMLALYKXCYYDMNMDQMXMCZNNCYBZKKYFLMCHCMLHXRCJJHSYLNMTJZGZGYWJXSRXCWJGJQHQZDQJDCJJZKJKGDZQGJJYJYLXZXXCDQHHHEYTMHLFSBDJSYYSHFYSTCZQLPBDRFRZTZYKYWHSZYQKWDQZRKMSYNBCRXQBJYFAZPZZEDZCJYWBCJWHYJBQSZYWRYSZPTDKZPFPBNZTKLQYHBBZPNPPTYZZYBQNYDCPJMMCYCQMCYFZZDCMNLFPBPLNGQJTBTTNJZPZBBZNJKLJQYLNBZQHKSJZNGGQSZZKYXSHPZSNBCGZKDDZQANZHJKDRTLZLSWJLJZLYWTJNDJZJHXYAYNCBGTZCSSQMNJPJYTYSWXZFKWJQTKHTZPLBHSNJZSYZBWZZZZLSYLSBJHDWWQPSLMMFBJDWAQYZTCJTBNNWZXQXCDSLQGDSDPDZHJTQQPSWLYYJZLGYXYZLCTCBJTKTYCZJTQKBSJLGMGZDMCSGPYNJZYQYYKNXRPWSZXMTNCSZZYXYBYHYZAXYWQCJTLLCKJJTJHGDXDXYQYZZBYWDLWQCGLZGJGQRQZCZSSBCRPCSKYDZNXJSQGXSSJMYDNSTZTPBDLTKZWXQWQTZEXNQCZGWEZKSSBYBRTSSSLCCGBPSZQSZLCCGLLLZXHZQTHCZMQGYZQZNMCOCSZJMMZSQPJYGQLJYJPPLDXRGZYXCCSXHSHGTZNLZWZKJCXTCFCJXLBMQBCZZWPQDNHXLJCTHYZLGYLNLSZZPCXDSCQQHJQKSXZPBAJYEMSMJTZDXLCJYRYYNWJBNGZZTMJXLTBSLYRZPYLSSCNXPHLLHYLLQQZQLXYMRSYCXZLMMCZLTZSDWTJJLLNZGGQXPFSKYGYGHBFZPDKMWGHCXMSGDXJMCJZDYCABXJDLNBCDQYGSKYDQTXDJJYXMSZQAZDZFSLQXYJSJZYLBTXXWXQQZBJZUFBBLYLWDSLJHXJYZJWTDJCZFQZQZZDZSXZZQLZCDZFJHYSPYMPQZMLPPLFFXJJNZZYLSJEYQZFPFZKSYWJJJHRDJZZXTXXGLGHYDXCSKYSWMMZCWYBAZBJKSHFHJCXMHFQHYXXYZFTSJYZFXYXPZLCHMZMBXHZZSXYFYMNCWDABAZLXKTCSHHXKXJJZJSTHYGXSXYYHHHJWXKZXSSBZZWHHHCWTZZZPJXSNXQQJGZYZYWLLCWXZFXXYXYHXMKYYSWSQMNLNAYCYSPMJKHWCQHYLAJJMZXHMMCNZHBHXCLXTJPLTXYJHDYYLTTXFSZHYXXSJBJYAYRSMXYPLCKDUYHLXRLNLLSTYZYYQYGYHHSCCSMZCTZQXKYQFPYYRPFFLKQUNTSZLLZMWWTCQQYZWTLLMLMPWMBZSSTZRBPDDTLQJJBXZCSRZQQYGWCSXFWZLXCCRSZDZMCYGGDZQSGTJSWLJMYMMZYHFBJDGYXCCPSHXNZCSBSJYJGJMPPWAFFYFNXHYZXZYLREMZGZCYZSSZDLLJCSQFNXZKPTXZGXJJGFMYYYSNBTYLBNLHPFZDCYFBMGQRRSSSZXYSGTZRNYDZZCDGPJAFJFZKNZBLCZSZPSGCYCJSZLMLRSZBZZLDLSLLYSXSQZQLYXZLSKKBRXBRBZCYCXZZZEEYFGKLZLYYHGZSGZLFJHGTGWKRAAJYZKZQTSSHJJXDCYZUYJLZYRZDQQHGJZXSSZBYKJPBFRTJXLLFQWJHYLQTYMBLPZDXTZYGBDHZZRBGXHWNJTJXLKSCFSMWLSDQYSJTXKZSCFWJLBXFTZLLJZLLQBLSQMQQCGCZFPBPHZCZJLPYYGGDTGWDCFCZQYYYQYSSCLXZSKLZZZGFFCQNWGLHQYZJJCZLQZZYJPJZZBPDCCMHJGXDQDGDLZQMFGPSYTSDYFWWDJZJYSXYYCZCYHZWPBYKXRYLYBHKJKSFXTZJMMCKHLLTNYYMSYXYZPYJQYCSYCWMTJJKQYRHLLQXPSGTLYYCLJSCPXJYZFNMLRGJJTYZBXYZMSJYJHHFZQMSYXRSZCWTLRTQZSSTKXGQKGSPTGCZNJSJCQCXHMXGGZTQYDJKZDLBZSXJLHYQGGGTHQSZPYHJHHGYYGKGGCWJZZYLCZLXQSFTGZSLLLMLJSKCTBLLZZSZMMNYTPZSXQHJCJYQXYZXZQZCPSHKZZYSXCDFGMWQRLLQXRFZTLYSTCTMJCXJJXHJNXTNRZTZFQYHQGLLGCXSZSJDJLJCYDSJTLNYXHSZXCGJZYQPYLFHDJSBPCCZHJJJQZJQDYBSSLLCMYTTMQTBHJQNNYGKYRQYQMZGCJKPDCGMYZHQLLSLLCLMHOLZGDYYFZSLJCQZLYLZQJESHNYLLJXGJXLYSYYYXNBZLJSSZCQQCJYLLZLTJYLLZLLBNYLGQCHXYYXOXCXQKYJXXXYKLXSXXYQXCYKQXQCSGYXXYQXYGYTQOHXHXPYXXXULCYEYCHZZCBWQBBWJQZSCSZSSLZYLKDESJZWMYMCYTSDSXXSCJPQQSQYLYYZYCMDJDZYWCBTJSYDJKCYDDJLBDJJSODZYSYXQQYXDHHGQQYQHDYXWGMMMAJDYBBBPPBCMUUPLJZSMTXERXJMHQNUTPJDCBSSMSSSTKJTSSMMTRCPLZSZMLQDSDMJMQPNQDXCFYNBFSDQXYXHYAYKQYDDLQYYYSSZBYDSLNTFQTZQPZMCHDHCZCWFDXTMYQSPHQYYXSRGJCWTJTZZQMGWJJTJHTQJBBHWZPXXHYQFXXQYWYYHYSCDYDHHQMNMTMWCPBSZPPZZGLMZFOLLCFWHMMSJZTTDHZZYFFYTZZGZYSKYJXQYJZQBHMBZZLYGHGFMSHPZFZSNCLPBQSNJXZSLXXFPMTYJYGBXLLDLXPZJYZJYHHZCYWHJYLSJEXFSZZYWXKZJLUYDTMLYMQJPWXYHXSKTQJEZRPXXZHHMHWQPWQLYJJQJJZSZCPHJLCHHNXJLQWZJHBMZYXBDHHYPZLHLHLGFWLCHYYTLHJXCJMSCPXSTKPNHQXSRTYXXTESYJCTLSSLSTDLLLWWYHDHRJZSFGXTSYCZYNYHTDHWJSLHTZDQDJZXXQHGYLTZPHCSQFCLNJTCLZPFSTPDYNYLGMJLLYCQHYSSHCHYLHQYQTMZYPBYWRFQYKQSYSLZDQJMPXYYSSRHZJNYWTQDFZBWWTWWRXCWHGYHXMKMYYYQMSMZHNGCEPMLQQMTCWCTMMPXJPJJHFXYYZSXZHTYBMSTSYJTTQQQYYLHYNPYQZLCYZHZWSMYLKFJXLWGXYPJYTYSYXYMZCKTTWLKSMZSYLMPWLZWXWQZSSAQSYXYRHSSNTSRAPXCPWCMGDXHXZDZYFJHGZTTSBJHGYZSZYSMYCLLLXBTYXHBBZJKSSDMALXHYCFYGMQYPJYCQXJLLLJGSLZGQLYCJCCZOTYXMTMTTLLWTGPXYMZMKLPSZZZXHKQYSXCTYJZYHXSHYXZKXLZWPSQPYHJWPJPWXQQYLXSDHMRSLZZYZWTTCYXYSZZSHBSCCSTPLWSSCJCHNLCGCHSSPHYLHFHHXJSXYLLNYLSZDHZXYLSXLWZYKCLDYAXZCMDDYSPJTQJZLNWQPSSSWCTSTSZLBLNXSMNYYMJQBQHRZWTYYDCHQLXKPZWBGQYBKFCMZWPZLLYYLSZYDWHXPSBCMLJBSCGBHXLQHYRLJXYSWXWXZSLDFHLSLYNJLZYFLYJYCDRJLFSYZFSLLCQYQFGJYHYXZLYLMSTDJCYHBZLLNWLXXYGYYHSMGDHXXHHLZZJZXCZZZCYQZFNGWPYLCPKPYYPMCLQKDGXZGGWQBDXZZKZFBXXLZXJTPJPTTBYTSZZDWSLCHZHSLTYXHQLHYXXXYYZYSWTXZKHLXZXZPYHGCHKCFSYHUTJRLXFJXPTZTWHPLYXFCRHXSHXKYXXYHZQDXQWULHYHMJTBFLKHTXCWHJFWJCFPQRYQXCYYYQYGRPYWSGSUNGWCHKZDXYFLXXHJJBYZWTSXXNCYJJYMSWZJQRMHXZWFQSYLZJZGBHYNSLBGTTCSYBYXXWXYHXYYXNSQYXMQYWRGYQLXBBZLJSYLPSYTJZYHYZAWLRORJMKSCZJXXXYXCHDYXRYXXJDTSQFXLYLTSFFYXLMTYJMJUYYYXLTZCSXQZQHZXLYYXZHDNBRXXXJCTYHLBRLMBRLLAXKYLLLJLYXXLYCRYLCJTGJCMTLZLLCYZZPZPCYAWHJJFYBDYYZSMPCKZDQYQPBPCJPDCYZMDPBCYYDYCNNPLMTMLRMFMMGWYZBSJGYGSMZQQQZTXMKQWGXLLPJGZBQCDJJJFPKJKCXBLJMSWMDTQJXLDLPPBXCWRCQFBFQJCZAHZGMYKPHYYHZYKNDKZMBPJYXPXYHLFPNYYGXJDBKXNXHJMZJXSTRSTLDXSKZYSYBZXJLXYSLBZYSLHXJPFXPQNBYLLJQKYGZMCYZZYMCCSLCLHZFWFWYXZMWSXTYNXJHPYYMCYSPMHYSMYDYSHQYZCHMJJMZCAAGCFJBBHPLYZYLXXSDJGXDHKXXTXXNBHRMLYJSLTXMRHNLXQJXYZLLYSWQGDLBJHDCGJYQYCMHWFMJYBMBYJYJWYMDPWHXQLDYGPDFXXBCGJSPCKRSSYZJMSLBZZJFLJJJLGXZGYXYXLSZQYXBEXYXHGCXBPLDYHWETTWWCJMBTXCHXYQXLLXFLYXLLJLSSFWDPZSMYJCLMWYTCZPCHQEKCQBWLCQYDPLQPPQZQFJQDJHYMMCXTXDRMJWRHXCJZYLQXDYYNHYYHRSLSRSYWWZJYMTLTLLGTQCJZYABTCKZCJYCCQLJZQXALMZYHYWLWDXZXQDLLQSHGPJFJLJHJABCQZDJGTKHSSTCYJLPSWZLXZXRWGLDLZRLZXTGSLLLLZLYXXWGDZYGBDPHZPBRLWSXQBPFDWOFMWHLYPCBJCCLDMBZPBZZLCYQXLDOMZBLZWPDWYYGDSTTHCSQSCCRSSSYSLFYBFNTYJSZDFNDPDHDZZMBBLSLCMYFFGTJJQWFTMTPJWFNLBZCMMJTGBDZLQLPYFHYYMJYLSDCHDZJWJCCTLJCLDTLJJCPDDSQDSSZYBNDBJLGGJZXSXNLYCYBJXQYCBYLZCFZPPGKCXZDZFZTJJFJSJXZBNZYJQTTYJYHTYCZHYMDJXTTMPXSPLZCDWSLSHXYPZGTFMLCJTYCBPMGDKWYCYZCDSZZYHFLYCTYGWHKJYYLSJCXGYWJCBLLCSNDDBTZBSCLYZCZZSSQDLLMQYYHFSLQLLXFTYHABXGWNYWYYPLLSDLDLLBJCYXJZMLHLJDXYYQYTDLLLBUGBFDFBBQJZZMDPJHGCLGMJJPGAEHHBWCQXAXHHHZCHXYPHJAXHLPHJPGPZJQCQZGJJZZUZDMQYYBZZPHYHYBWHAZYJHYKFGDPFQSDLZMLJXKXGALXZDAGLMDGXMWZQYXXDXXPFDMMSSYMPFMDMMKXKSYZYSHDZKXSYSMMZZZMSYDNZZCZXFPLSTMZDNMXCKJMZTYYMZMZZMSXHHDCZJEMXXKLJSTLWLSQLYJZLLZJSSDPPMHNLZJCZYHMXXHGZCJMDHXTKGRMXFWMCGMWKDTKSXQMMMFZZYDKMSCLCMPCGMHSPXQPZDSSLCXKYXTWLWJYAHZJGZQMCSNXYYMMPMLKJXMHLMLQMXCTKZMJQYSZJSYSZHSYJZJCDAJZYBSDQJZGWZQQXFKDMSDJLFWEHKZQKJPEYPZYSZCDWYJFFMZZYLTTDZZEFMZLBNPPLPLPEPSZALLTYLKCKQZKGENQLWAGYXYDPXLHSXQQWQCQXQCLHYXXMLYCCWLYMQYSKGCHLCJNSZKPYZKCQZQLJPDMDZHLASXLBYDWQLWDNBQCRYDDZTJYBKBWSZDXDTNPJDTCTQDFXQQMGNXECLTTBKPWSLCTYQLPWYZZKLPYGZCQQPLLKCCYLPQMZCZQCLJSLQZDJXLDDHPZQDLJJXZQDXYZQKZLJCYQDYJPPYPQYKJYRMPCBYMCXKLLZLLFQPYLLLMBSGLCYSSLRSYSQTMXYXZQZFDZUYSYZTFFMZZSMZQHZSSCCMLYXWTPZGXZJGZGSJSGKDDHTQGGZLLBJDZLCBCHYXYZHZFYWXYZYMSDBZZYJGTSMTFXQYXQSTDGSLNXDLRYZZLRYYLXQHTXSRTZNGZXBNQQZFMYKMZJBZYMKBPNLYZPBLMCNQYZZZSJZHJCTZKHYZZJRDYZHNPXGLFZTLKGJTCTSSYLLGZRZBBQZZKLPKLCZYSSUYXBJFPNJZZXCDWXZYJXZZDJJKGGRSRJKMSMZJLSJYWQSKYHQJSXPJZZZLSNSHRNYPZTWCHKLPSRZLZXYJQXQKYSJYCZTLQZYBBYBWZPQDWWYZCYTJCJXCKCWDKKZXSGKDZXWWYYJQYYTCYTDLLXWKCZKKLCCLZCQQDZLQLCSFQCHQHSFSMQZZLNBJJZBSJHTSZDYSJQJPDLZCDCWJKJZZLPYCGMZWDJJBSJQZSYZYHHXJPBJYDSSXDZNCGLQMBTSFSBPDZDLZNFGFJGFSMPXJQLMBLGQCYYXBQKDJJQYRFKZTJDHCZKLBSDZCFJTPLLJGXHYXZCSSZZXSTJYGKGCKGYOQXJPLZPBPGTGYJZGHZQZZLBJLSQFZGKQQJZGYCZBZQTLDXRJXBSXXPZXHYZYCLWDXJJHXMFDZPFZHQHQMQGKSLYHTYCGFRZGNQXCLPDLBZCSCZQLLJBLHBZCYPZZPPDYMZZSGYHCKCPZJGSLJLNSCDSLDLXBMSTLDDFJMKDJDHZLZXLSZQPQPGJLLYBDSZGQLBZLSLKYYHZTTNTJYQTZZPSZQZTLLJTYYLLQLLQYZQLBDZLSLYYZYMDFSZSNHLXZNCZQZPBWSKRFBSYZMTHBLGJPMCZZLSTLXSHTCSYZLZBLFEQHLXFLCJLYLJQCBZLZJHHSSTBRMHXZHJZCLXFNBGXGTQJCZTMSFZKJMSSNXLJKBHSJXNTNLZDNTLMSJXGZJYJCZXYJYJWRWWQNZTNFJSZPZSHZJFYRDJSFSZJZBJFZQZZHZLXFYSBZQLZSGYFTZDCSZXZJBQMSZKJRHYJZCKMJKHCHGTXKXQGLXPXFXTRTYLXJXHDTSJXHJZJXZWZLCQSBTXWXGXTXXHXFTSDKFJHZYJFJXRZSDLLLTQSQQZQWZXSYQTWGWBZCGZLLYZBCLMQQTZHZXZXLJFRMYZFLXYSQXXJKXRMQDZDMMYYBSQBHGZMWFWXGMXLZPYYTGZYCCDXYZXYWGSYJYZNBHPZJSQSYXSXRTFYZGRHZTXSZZTHCBFCLSYXZLZQMZLMPLMXZJXSFLBYZMYQHXJSXRXSQZZZSSLYFRCZJRCRXHHZXQYDYHXSJJHZCXZBTYNSYSXJBQLPXZQPYMLXZKYXLXCJLCYSXXZZLXDLLLJJYHZXGYJWKJRWYHCPSGNRZLFZWFZZNSXGXFLZSXZZZBFCSYJDBRJKRDHHGXJLJJTGXJXXSTJTJXLYXQFCSGSWMSBCTLQZZWLZZKXJMLTMJYHSDDBXGZHDLBMYJFRZFSGCLYJBPMLYSMSXLSZJQQHJZFXGFQFQBPXZGYYQXGZTCQWYLTLGWSGWHRLFSFGZJMGMGBGTJFSYZZGZYZAFLSSPMLPFLCWBJZCLJJMZLPJJLYMQDMYYYFBGYGYZMLYZDXQYXRQQQHSYYYQXYLJTYXFSFSLLGNQCYHYCWFHCCCFXPYLYPLLZYXXXXXKQHHXSHJZCFZSCZJXCPZWHHHHHAPYLQALPQAFYHXDYLUKMZQGGGDDESRNNZLTZGCHYPPYSQJJHCLLJTOLNJPZLJLHYMHEYDYDSQYCDDHGZUNDZCLZYZLLZNTNYZGSLHSLPJJBDGWXPCDUTJCKLKCLWKLLCASSTKZZDNQNTTLYYZSSYSSZZRYLJQKCQDHHCRXRZYDGRGCWCGZQFFFPPJFZYNAKRGYWYQPQXXFKJTSZZXSWZDDFBBXTBGTZKZNPZZPZXZPJSZBMQHKCYXYLDKLJNYPKYGHGDZJXXEAHPNZKZTZCMXCXMMJXNKSZQNMNLWBWWXJKYHCPSTMCSQTZJYXTPCTPDTNNPGLLLZSJLSPBLPLQHDTNJNLYYRSZFFJFQWDPHZDWMRZCCLODAXNSSNYZRESTYJWJYJDBCFXNMWTTBYLWSTSZGYBLJPXGLBOCLHPCBJLTMXZLJYLZXCLTPNCLCKXTPZJSWCYXSFYSZDKNTLBYJCYJLLSTGQCBXRYZXBXKLYLHZLQZLNZCXWJZLJZJNCJHXMNZZGJZZXTZJXYCYYCXXJYYXJJXSSSJSTSSTTPPGQTCSXWZDCSYFPTFBFHFBBLZJCLZZDBXGCXLQPXKFZFLSYLTUWBMQJHSZBMDDBCYSCCLDXYCDDQLYJJWMQLLCSGLJJSYFPYYCCYLTJANTJJPWYCMMGQYYSXDXQMZHSZXPFTWWZQSWQRFKJLZJQQYFBRXJHHFWJJZYQAZMYFRHCYYBYQWLPEXCCZSTYRLTTDMQLYKMBBGMYYJPRKZNPBSXYXBHYZDJDNGHPMFSGMWFZMFQMMBCMZZCJJLCNUXYQLMLRYGQZCYXZLWJGCJCGGMCJNFYZZJHYCPRRCMTZQZXHFQGTJXCCJEAQCRJYHPLQLSZDJRBCQHQDYRHYLYXJSYMHZYDWLDFRYHBPYDTSSCNWBXGLPZMLZZTQSSCPJMXXYCSJYTYCGHYCJWYRXXLFEMWJNMKLLSWTXHYYYNCMMCWJDQDJZGLLJWJRKHPZGGFLCCSCZMCBLTBHBQJXQDSPDJZZGKGLFQYWBZYZJLTSTDHQHCTCBCHFLQMPWDSHYYTQWCNZZJTLBYMBPDYYYXSQKXWYYFLXXNCWCXYPMAELYKKJMZZZBRXYYQJFLJPFHHHYTZZXSGQQMHSPGDZQWBWPJHZJDYSCQWZKTXXSQLZYYMYSDZGRXCKKUJLWPYSYSCSYZLRMLQSYLJXBCXTLWDQZPCYCYKPPPNSXFYZJJRCEMHSZMSXLXGLRWGCSTLRSXBZGBZGZTCPLUJLSLYLYMTXMTZPALZXPXJTJWTCYYZLBLXBZLQMYLXPGHDSLSSDMXMBDZZSXWHAMLCZCPJMCNHJYSNSYGCHSKQMZZQDLLKABLWJXSFMOCDXJRRLYQZKJMYBYQLYHETFJZFRFKSRYXFJTWDSXXSYSQJYSLYXWJHSNLXYYXHBHAWHHJZXWMYLJCSSLKYDZTXBZSYFDXGXZJKHSXXYBSSXDPYNZWRPTQZCZENYGCXQFJYKJBZMLJCMQQXUOXSLYXXLYLLJDZBTYMHPFSTTQQWLHOKYBLZZALZXQLHZWRRQHLSTMYPYXJJXMQSJFNBXYXYJXXYQYLTHYLQYFMLKLJTMLLHSZWKZHLJMLHLJKLJSTLQXYLMBHHLNLZXQJHXCFXXLHYHJJGBYZZKBXSCQDJQDSUJZYYHZHHMGSXCSYMXFEBCQWWRBPYYJQTYZCYQYQQZYHMWFFHGZFRJFCDPXNTQYZPDYKHJLFRZXPPXZDBBGZQSTLGDGYLCQMLCHHMFYWLZYXKJLYPQHSYWMQQGQZMLZJNSQXJQSYJYCBEHSXFSZPXZWFLLBCYYJDYTDTHWZSFJMQQYJLMQXXLLDTTKHHYBFPWTYYSQQWNQWLGWDEBZWCMYGCULKJXTMXMYJSXHYBRWFYMWFRXYQMXYSZTZZTFYKMLDHQDXWYYNLCRYJBLPSXCXYWLSPRRJWXHQYPHTYDNXHHMMYWYTZCSQMTSSCCDALWZTCPQPYJLLQZYJSWXMZZMMYLMXCLMXCZMXMZSQTZPPQQBLPGXQZHFLJJHYTJSRXWZXSCCDLXTYJDCQJXSLQYCLZXLZZXMXQRJMHRHZJBHMFLJLMLCLQNLDXZLLLPYPSYJYSXCQQDCMQJZZXHNPNXZMEKMXHYKYQLXSXTXJYYHWDCWDZHQYYBGYBCYSCFGPSJNZDYZZJZXRZRQJJYMCANYRJTLDPPYZBSTJKXXZYPFDWFGZZRPYMTNGXZQBYXNBUFNQKRJQZMJEGRZGYCLKXZDSKKNSXKCLJSPJYYZLQQJYBZSSQLLLKJXTBKTYLCCDDBLSPPFYLGYDTZJYQGGKQTTFZXBDKTYYHYBBFYTYYBCLPDYTGDHRYRNJSPTCSNYJQHKLLLZSLYDXXWBCJQSPXBPJZJCJDZFFXXBRMLAZHCSNDLBJDSZBLPRZTSWSBXBCLLXXLZDJZSJPYLYXXYFTFFFBHJJXGBYXJPMMMPSSJZJMTLYZJXSWXTYLEDQPJMYGQZJGDJLQJWJQLLSJGJGYGMSCLJJXDTYGJQJQJCJZCJGDZZSXQGSJGGCXHQXSNQLZZBXHSGZXCXYLJXYXYYDFQQJHJFXDHCTXJYRXYSQTJXYEFYYSSYYJXNCYZXFXMSYSZXYYSCHSHXZZZGZZZGFJDLTYLNPZGYJYZYYQZPBXQBDZTZCZYXXYHHSQXSHDHGQHJHGYWSZTMZMLHYXGEBTYLZKQWYTJZRCLEKYSTDBCYKQQSAYXCJXWWGSBHJYZYDHCSJKQCXSWXFLTYNYZPZCCZJQTZWJQDZZZQZLJJXLSBHPYXXPSXSHHEZTXFPTLQYZZXHYTXNCFZYYHXGNXMYWXTZSJPTHHGYMXMXQZXTSBCZYJYXXTYYZYPCQLMMSZMJZZLLZXGXZAAJZYXJMZXWDXZSXZDZXLEYJJZQBHZWZZZQTZPSXZTDSXJJJZNYAZPHXYYSRNQDTHZHYYKYJHDZXZLSWCLYBZYECWCYCRYLCXNHZYDZYDYJDFRJJHTRSQTXYXJRJHOJYNXELXSFSFJZGHPZSXZSZDZCQZBYYKLSGSJHCZSHDGQGXYZGXCHXZJWYQWGYHKSSEQZZNDZFKWYSSTCLZSTSYMCDHJXXYWEYXCZAYDMPXMDSXYBSQMJMZJMTZQLPJYQZCGQHXJHHLXXHLHDLDJQCLDWBSXFZZYYSCHTYTYYBHECXHYKGJPXHHYZJFXHWHBDZFYZBCAPNPGNYDMSXHMMMMAMYNBYJTMPXYYMCTHJBZYFCGTYHWPHFTWZZEZSBZEGPFMTSKFTYCMHFLLHGPZJXZJGZJYXZSBBQSCZZLZCCSTPGXMJSFTCCZJZDJXCYBZLFCJSYZFGSZLYBCWZZBYZDZYPSWYJZXZBDSYUXLZZBZFYGCZXBZHZFTPBGZGEJBSTGKDMFHYZZJHZLLZZGJQZLSFDJSSCBZGPDLFZFZSZYZYZSYGCXSNXXCHCZXTZZLJFZGQSQYXZJQDCCZTQCDXZJYQJQCHXZTDLGSCXZSYQJQTZWLQDQZTQCHQQJZYEZZZPBWKDJFCJPZTYPQYQTTYNLMBDKTJZPQZQZZFPZSBNJLGYJDXJDZZKZGQKXDLPZJTCJDQBXDJQJSTCKNXBXZMSLYJCQMTJQWWCJQNJNLLLHJCWQTBZQYDZCZPZZDZYDDCYZZZCCJTTJFZDPRRTZTJDCQTQZDTJNPLZBCLLCTZSXKJZQZPZLBZRBTJDCXFCZDBCCJJLTQQPLDCGZDBBZJCQDCJWYNLLZYZCCDWLLXWZLXRXNTQQCZXKQLSGDFQTDDGLRLAJJTKUYMKQLLTZYTDYYCZGJWYXDXFRSKSTQTENQMRKQZHHQKDLDAZFKYPBGGPZREBZZYKZZSPEGJXGYKQZZZSLYSYYYZWFQZYLZZLZHWCHKYPQGNPGBLPLRRJYXCCSYYHSFZFYBZYYTGZXYLXCZWXXZJZBLFFLGSKHYJZEYJHLPLLLLCZGXDRZELRHGKLZZYHZLYQSZZJZQLJZFLNBHGWLCZCFJYSPYXZLZLXGCCPZBLLCYBBBBUBBCBPCRNNZCZYRBFSRLDCGQYYQXYGMQZWTZYTYJXYFWTEHZZJYWLCCNTZYJJZDEDPZDZTSYQJHDYMBJNYJZLXTSSTPHNDJXXBYXQTZQDDTJTDYYTGWSCSZQFLSHLGLBCZPHDLYZJYCKWTYTYLBNYTSDSYCCTYSZYYEBHEXHQDTWNYGYCLXTSZYSTQMYGZAZCCSZZDSLZCLZRQXYYELJSBYMXSXZTEMBBLLYYLLYTDQYSHYMRQWKFKBFXNXSBYCHXBWJYHTQBPBSBWDZYLKGZSKYHXQZJXHXJXGNLJKZLYYCDXLFYFGHLJGJYBXQLYBXQPQGZTZPLNCYPXDJYQYDYMRBESJYYHKXXSTMXRCZZYWXYQYBMCLLYZHQYZWQXDBXBZWZMSLPDMYSKFMZKLZCYQYCZLQXFZZYDQZPZYGYJYZMZXDZFYFYTTQTZHGSPCZMLCCYTZXJCYTJMKSLPZHYSNZLLYTPZCTZZCKTXDHXXTQCYFKSMQCCYYAZHTJPCYLZLYJBJXTPNYLJYYNRXSYLMMNXJSMYBCSYSYLZYLXJJQYLDZLPQBFZZBLFNDXQKCZFYWHGQMRDSXYCYTXNQQJZYYPFZXDYZFPRXEJDGYQBXRCNFYYQPGHYJDYZXGRHTKYLNWDZNTSMPKLBTHBPYSZBZTJZSZZJTYYXZPHSSZZBZCZPTQFZMYFLYPYBBJQXZMXXDJMTSYSKKBJZXHJCKLPSMKYJZCXTMLJYXRZZQSLXXQPYZXMKYXXXJCLJPRMYYGADYSKQLSNDHYZKQXZYZTCGHZTLMLWZYBWSYCTBHJHJFCWZTXWYTKZLXQSHLYJZJXTMPLPYCGLTBZZTLZJCYJGDTCLKLPLLQPJMZPAPXYZLKKTKDZCZZBNZDYDYQZJYJGMCTXLTGXSZLMLHBGLKFWNWZHDXUHLFMKYSLGXDTWWFRJEJZTZHYDXYKSHWFZCQSHKTMQQHTZHYMJDJSKHXZJZBZZXYMPAGQMSTPXLSKLZYNWRTSQLSZBPSPSGZWYHTLKSSSWHZZLYYTNXJGMJSZSUFWNLSOZTXGXLSAMMLBWLDSZYLAKQCQCTMYCFJBSLXCLZZCLXXKSBZQCLHJPSQPLSXXCKSLNHPSFQQYTXYJZLQLDXZQJZDYYDJNZPTUZDSKJFSLJHYLZSQZLBTXYDGTQFDBYAZXDZHZJNHHQBYKNXJJQCZMLLJZKSPLDYCLBBLXKLELXJLBQYCXJXGCNLCQPLZLZYJTZLJGYZDZPLTQCSXFDMNYCXGBTJDCZNBGBQYQJWGKFHTNPYQZQGBKPBBYZMTJDYTBLSQMPSXTBNPDXKLEMYYCJYNZCTLDYKZZXDDXHQSHDGMZSJYCCTAYRZLPYLTLKXSLZCGGEXCLFXLKJRTLQJAQZNCMBYDKKCXGLCZJZXJHPTDJJMZQYKQSECQZDSHHADMLZFMMZBGNTJNNLGBYJBRBTMLBYJDZXLCJLPLDLPCQDHLXZLYCBLCXZZJADJLNZMMSSSMYBHBSQKBHRSXXJMXSDZNZPXLGBRHWGGFCXGMSKLLTSJYYCQLTSKYWYYHYWXBXQYWPYWYKQLSQPTNTKHQCWDQKTWPXXHCPTHTWUMSSYHBWCRWXHJMKMZNGWTMLKFGHKJYLSYYCXWHYECLQHKQHTTQKHFZLDXQWYZYYDESBPKYRZPJFYYZJCEQDZZDLATZBBFJLLCXDLMJSSXEGYGSJQXCWBXSSZPDYZCXDNYXPPZYDLYJCZPLTXLSXYZYRXCYYYDYLWWNZSAHJSYQYHGYWWAXTJZDAXYSRLTDPSSYYFNEJDXYZHLXLLLZQZSJNYQYQQXYJGHZGZCYJCHZLYCDSHWSHJZYJXCLLNXZJJYYXNFXMWFPYLCYLLABWDDHWDXJMCXZTZPMLQZHSFHZYNZTLLDYWLSLXHYMMYLMBWWKYXYADTXYLLDJPYBPWUXJMWMLLSAFDLLYFLBHHHBQQLTZJCQJLDJTFFKMMMBYTHYGDCQRDDWRQJXNBYSNWZDBYYTBJHPYBYTTJXAAHGQDQTMYSTQXKBTZPKJLZRBEQQSSMJJBDJOTGTBXPGBKTLHQXJJJCTHXQDWJLWRFWQGWSHCKRYSWGFTGYGBXSDWDWRFHWYTJJXXXJYZYSLPYYYPAYXHYDQKXSHXYXGSKQHYWFDDDPPLCJLQQEEWXKSYYKDYPLTJTHKJLTCYYHHJTTPLTZZCDLTHQKZXQYSTEEYWYYZYXXYYSTTJKLLPZMCYHQGXYHSRMBXPLLNQYDQHXSXXWGDQBSHYLLPJJJTHYJKYPPTHYYKTYEZYENMDSHLCRPQFDGFXZPSFTLJXXJBSWYYSKSFLXLPPLBBBLBSFXFYZBSJSSYLPBBFFFFSSCJDSTZSXZRYYSYFFSYZYZBJTBCTSBSDHRTJJBYTCXYJEYLXCBNEBJDSYXYKGSJZBXBYTFZWGENYHHTHZHHXFWGCSTBGXKLSXYWMTMBYXJSTZSCDYQRCYTWXZFHMYMCXLZNSDJTTTXRYCFYJSBSDYERXJLJXBBDEYNJGHXGCKGSCYMBLXJMSZNSKGXFBNBPTHFJAAFXYXFPXMYPQDTZCXZZPXRSYWZDLYBBKTYQPQJPZYPZJZNJPZJLZZFYSBTTSLMPTZRTDXQSJEHBZYLZDHLJSQMLHTXTJECXSLZZSPKTLZKQQYFSYGYWPCPQFHQHYTQXZKRSGTTSQCZLPTXCDYYZXSQZSLXLZMYCPCQBZYXHBSXLZDLTCDXTYLZJYYZPZYZLTXJSJXHLPMYTXCQRBLZSSFJZZTNJYTXMYJHLHPPLCYXQJQQKZZSCPZKSWALQSBLCCZJSXGWWWYGYKTJBBZTDKHXHKGTGPBKQYSLPXPJCKBMLLXDZSTBKLGGQKQLSBKKTFXRMDKBFTPZFRTBBRFERQGXYJPZSSTLBZTPSZQZSJDHLJQLZBPMSMMSXLQQNHKNBLRDDNXXDHDDJCYYGYLXGZLXSYGMQQGKHBPMXYXLYTQWLWGCPBMQXCYZYDRJBHTDJYHQSHTMJSBYPLWHLZFFNYPMHXXHPLTBQPFBJWQDBYGPNZTPFZJGSDDTQSHZEAWZZYLLTYYBWJKXXGHLFKXDJTMSZSQYNZGGSWQSPHTLSSKMCLZXYSZQZXNCJDQGZDLFNYKLJCJLLZLMZZNHYDSSHTHZZLZZBBHQZWWYCRZHLYQQJBEYFXXXWHSRXWQHWPSLMSSKZTTYGYQQWRSLALHMJTQJSMXQBJJZJXZYZKXBYQXBJXSHZTSFJLXMXZXFGHKZSZGGYLCLSARJYHSLLLMZXELGLXYDJYTLFBHBPNLYZFBBHPTGJKWETZHKJJXZXXGLLJLSTGSHJJYQLQZFKCGNNDJSSZFDBCTWWSEQFHQJBSAQTGYPQLBXBMMYWXGSLZHGLZGQYFLZBYFZJFRYSFMBYZHQGFWZSYFYJJPHZBYYZFFWODGRLMFTWLBZGYCQXCDJYGZYYYYTYTYDWEGAZYHXJLZYYHLRMGRXXZCLHNELJJTJTPWJYBJJBXJJTJTEEKHWSLJPLPSFYZPQQBDLQJJTYYQLYZKDKSQJYYQZLDQTGJQYZJSUCMRYQTHTEJMFCTYHYPKMHYZWJDQFHYYXWSHCTXRLJHQXHCCYYYJLTKTTYTMXGTCJTZAYYOCZLYLBSZYWJYTSJYHBYSHFJLYGJXXTMZYYLTXXYPZLXYJZYZYYPNHMYMDYYLBLHLSYYQQLLNJJYMSOYQBZGDLYXYLCQYXTSZEGXHZGLHWBLJHEYXTWQMAKBPQCGYSHHEGQCMWYYWLJYJHYYZLLJJYLHZYHMGSLJLJXCJJYCLYCJPCPZJZJMMYLCQLNQLJQJSXYJMLSZLJQLYCMMHCFMMFPQQMFYLQMCFFQMMMMHMZNFHHJGTTHHKHSLNCHHYQDXTMMQDCYZYXYQMYQYLTDCYYYZAZZCYMZYDLZFFFMMYCQZWZZMABTBYZTDMNZZGGDFTYPCGQYTTSSFFWFDTZQSSYSTWXJHXYTSXXYLBYQHWWKXHZXWZNNZZJZJJQJCCCHYYXBZXZCYZTLLCQXYNJYCYYCYNZZQYYYEWYCZDCJYCCHYJLBTZYYCQWMPWPYMLGKDLDLGKQQBGYCHJXY";
//此处收录了375个多音字,数据来自于http://www.51window.net/page/pinyin
const oMultiDiff = {"19969":"DZ", "19975":"WM", "19988":"QJ", "20048":"YL", "20056":"SC", "20060":"NM", "20094":"QG", "20127":"QJ", "20167":"QC", "20193":"YG", "20250":"KH", "20256":"ZC", "20282":"SC", "20285":"QJG", "20291":"TD", "20314":"YD", "20340":"NE", "20375":"TD", "20389":"YJ", "20391":"CZ", "20415":"PB", "20446":"YS", "20447":"SQ", "20504":"TC", "20608":"KG", "20854":"QJ", "20857":"ZC", "20911":"PF", "20504":"TC", "20608":"KG", "20854":"QJ", "20857":"ZC", "20911":"PF", "20985":"AW", "21032":"PB", "21048":"XQ", "21049":"SC", "21089":"YS", "21119":"JC", "21242":"SB", "21273":"SC", "21305":"YP", "21306":"QO", "21330":"ZC", "21333":"SDC", "21345":"QK", "21378":"CA", "21397":"SC", "21414":"XS", "21442":"SC", "21477":"JG", "21480":"TD", "21484":"ZS", "21494":"YX", "21505":"YX", "21512":"HG", "21523":"XH", "21537":"PB", "21542":"PF", "21549":"KH", "21571":"E", "21574":"DA", "21588":"TD", "21589":"O", "21618":"ZC", "21621":"KHA", "21632":"ZJ", "21654":"KG", "21679":"LKG", "21683":"KH", "21710":"A", "21719":"YH", "21734":"WOE", "21769":"A", "21780":"WN", "21804":"XH", "21834":"A", "21899":"ZD", "21903":"RN", "21908":"WO", "21939":"ZC", "21956":"SA", "21964":"YA", "21970":"TD", "22003":"A", "22031":"JG", "22040":"XS", "22060":"ZC", "22066":"ZC", "22079":"MH", "22129":"XJ", "22179":"XA", "22237":"NJ", "22244":"TD", "22280":"JQ", "22300":"YH", "22313":"XW", "22331":"YQ", "22343":"YJ", "22351":"PH", "22395":"DC", "22412":"TD", "22484":"PB", "22500":"PB", "22534":"ZD", "22549":"DH", "22561":"PB", "22612":"TD", "22771":"KQ", "22831":"HB", "22841":"JG", "22855":"QJ", "22865":"XQ", "23013":"ML", "23081":"WM", "23487":"SX", "23558":"QJ", "23561":"YW", "23586":"YW", "23614":"YW", "23615":"SN", "23631":"PB", "23646":"ZS", "23663":"ZT", "23673":"YG", "23762":"TD", "23769":"ZS", "23780":"QJ", "23884":"QK", "24055":"XH", "24113":"DC", "24162":"ZC", "24191":"GA", "24273":"QJ", "24324":"NL", "24377":"TD", "24378":"QJ", "24439":"PF", "24554":"ZS", "24683":"TD", "24694":"WE", "24733":"LK", "24925":"TN", "25094":"ZG", "25100":"XQ", "25103":"XH", "25153":"PB", "25170":"PB", "25179":"KG", "25203":"PB", "25240":"ZS", "25282":"FB", "25303":"NA", "25324":"KG", "25341":"ZY", "25373":"WZ", "25375":"XJ", "25384":"A", "25457":"A", "25528":"SD", "25530":"SC", "25552":"TD", "25774":"ZC", "25874":"ZC", "26044":"YW", "26080":"WM", "26292":"PB", "26333":"PB", "26355":"ZY", "26366":"CZ", "26397":"ZC", "26399":"QJ", "26415":"ZS", "26451":"SB", "26526":"ZC", "26552":"JG", "26561":"TD", "26588":"JG", "26597":"CZ", "26629":"ZS", "26638":"YL", "26646":"XQ", "26653":"KG", "26657":"XJ", "26727":"HG", "26894":"ZC", "26937":"ZS", "26946":"ZC", "26999":"KJ", "27099":"KJ", "27449":"YQ", "27481":"XS", "27542":"ZS", "27663":"ZS", "27748":"TS", "27784":"SC", "27788":"ZD", "27795":"TD", "27812":"O", "27850":"PB", "27852":"MB", "27895":"SL", "27898":"PL", "27973":"QJ", "27981":"KH", "27986":"HX", "27994":"XJ", "28044":"YC", "28065":"WG", "28177":"SM", "28267":"QJ", "28291":"KH", "28337":"ZQ", "28463":"TL", "28548":"DC", "28601":"TD", "28689":"PB", "28805":"JG", "28820":"QG", "28846":"PB", "28952":"TD", "28975":"ZC", "29100":"A", "29325":"QJ", "29575":"SL", "29602":"FB", "30010":"TD", "30044":"CX", "30058":"PF", "30091":"YSP", "30111":"YN", "30229":"XJ", "30427":"SC", "30465":"SX", "30631":"YQ", "30655":"QJ", "30684":"QJG", "30707":"SD", "30729":"XH", "30796":"LG", "30917":"PB", "31074":"NM", "31085":"JZ", "31109":"SC", "31181":"ZC", "31192":"MLB", "31293":"JQ", "31400":"YX", "31584":"YJ", "31896":"ZN", "31909":"ZY", "31995":"XJ", "32321":"PF", "32327":"ZY", "32418":"HG", "32420":"XQ", "32421":"HG", "32438":"LG", "32473":"GJ", "32488":"TD", "32521":"QJ", "32527":"PB", "32562":"ZSQ", "32564":"JZ", "32735":"ZD", "32793":"PB", "33071":"PF", "33098":"XL", "33100":"YA", "33152":"PB", "33261":"CX", "33324":"BP", "33333":"TD", "33406":"YA", "33426":"WM", "33432":"PB", "33445":"JG", "33486":"ZN", "33493":"TS", "33507":"QJ", "33540":"QJ", "33544":"ZC", "33564":"XQ", "33617":"YT", "33632":"QJ", "33636":"XH", "33637":"YX", "33694":"WG", "33705":"PF", "33728":"YW", "33882":"SR", "34067":"WM", "34074":"YW", "34121":"QJ", "34255":"ZC", "34259":"XL", "34425":"JH", "34430":"XH", "34485":"KH", "34503":"YS", "34532":"HG", "34552":"XS", "34558":"YE", "34593":"ZL", "34660":"YQ", "34892":"XH", "34928":"SC", "34999":"QJ", "35048":"PB", "35059":"SC", "35098":"ZC", "35203":"TQ", "35265":"JX", "35299":"JX", "35782":"SZ", "35828":"YS", "35830":"E", "35843":"TD", "35895":"YG", "35977":"MH", "36158":"JG", "36228":"QJ", "36426":"XQ", "36466":"DC", "36710":"JC", "36711":"ZYG", "36767":"PB", "36866":"SK", "36951":"YW", "37034":"YX", "37063":"XH", "37218":"ZC", "37325":"ZC", "38063":"PB", "38079":"TD", "38085":"QY", "38107":"DC", "38116":"TD", "38123":"YD", "38224":"HG", "38241":"XTC", "38271":"ZC", "38415":"YE", "38426":"KH", "38461":"YD", "38463":"AE", "38466":"PB", "38477":"XJ", "38518":"YT", "38551":"WK", "38585":"ZC", "38704":"XS", "38739":"LJ", "38761":"GJ", "38808":"SQ", "39048":"JG", "39049":"XJ", "39052":"HG", "39076":"CZ", "39271":"XT", "39534":"TD", "39552":"TD", "39584":"PB", "39647":"SB", "39730":"LG", "39748":"TPB", "40109":"ZQ", "40479":"ND", "40516":"HG", "40536":"HG", "40583":"QJ", "40765":"YQ", "40784":"QJ", "40840":"YK", "40863":"QJG"};
//返回值:拼音首字母串数组
function makePy(str) {
	if (typeof (str) != "string") {
		throw new Error(-1, "\u51fd\u6570makePy\u9700\u8981\u5b57\u7b26\u4e32\u7c7b\u578b\u53c2\u6570!");
	}
	var arrResult = new Array(); //保存中间结果的数组
	for (var i = 0, len = str.length; i < len; i++) {
//获得unicode码
		var ch = str.charAt(i);
//检查该unicode码是否在处理范围之内,在则返回该码对映汉字的拼音首字母,不在则调用其它函数处理
		arrResult.push(checkCh(ch));
	}
//处理arrResult,返回所有可能的拼音首字母串数组
	return mkRslt(arrResult);
}
function checkCh(ch) {
	var uni = ch.charCodeAt(0);
//如果不在汉字处理范围之内,返回原字符,也可以调用自己的处理函数
	if (uni > 40869 || uni < 19968) {
		return ch;
	} //dealWithOthers(ch);
//检查是否是多音字,是按多音字处理,不是就直接在strChineseFirstPY字符串中找对应的首字母
	return (oMultiDiff[uni] ? oMultiDiff[uni] : (strChineseFirstPY.charAt(uni - 19968)));
}
function mkRslt(arr) {
	var arrRslt = [""];
	for (var i = 0, len = arr.length; i < len; i++) {
		var str = arr[i];
		var strlen = str.length;
		if (strlen == 1) {
			for (var k = 0; k < arrRslt.length; k++) {
				arrRslt[k] += str;
			}
		} else {
			var tmpArr = arrRslt.slice(0);
			arrRslt = [];
			for (k = 0; k < strlen; k++) {
//复制一个相同的arrRslt
				var tmp = tmpArr.slice(0);
//把当前字符str[k]添加到每个元素末尾
				for (var j = 0; j < tmp.length; j++) {
					tmp[j] += str.charAt(k);
				}
//把复制并修改后的数组连接到arrRslt上
				arrRslt = arrRslt.concat(tmp);
			}
		}
	}
	return arrRslt;
}
//两端去空格函数
String.prototype.trim = function () {
	return this.replace(/(^\s*)|(\s*$)/g, "");
};
export default {
    name:"Home",
    data(){
        return{
            picloading:false,
            tableData:[],
            canShowData:true,
            archives:{
                select:''
            },
            options2: [{
            value: 1,
            label: '图片',
            disabled: true
            },{
            value: 2,
            label: '音频',
            disabled: true
            }, {
            value: 3,
            label: '视频',
            disabled: true
            }, {
            value: 4,
            label: '文档',
            disabled: true
            },{
            value: 5,
            label: '其他',
            disabled: true
            },
            ],
            value2:'',
            bigdatas:{
                filePath:'',
                fileType:'',
                fileList:[],
            },
            fileTyepAccept:"",
            dialogTableVisible:false,
            showVideo:false,
            showAudio:false,
            showPicture:false,
            videoSrc:'',
            videoName:'',
            audioSrc:'',
            audioName:'',
            pictureSrc:'',
            picName:'',
            picIndex:'',
            options: [{
                id: '123',
                nodeName: '全宗',
                children:[]
            }],
            props: {
                value: 'id',
                label: 'nodeName',
                children: 'children'        
            },
            opChild:[],
            bigData:{
                column:'',
                keyword:'',
                rootNodeId:'',
                dataList:{
                    loading:true,
                    columnsDatas:[],
                    tableDatas:[],
                    columnsAjDatas:[],
                    tableDatas:[],
                    filePath:'',
                },
                dataListShow:false,
                AjdataListShow:false,

            }
                    
        }
    },
    mounted(){
        this.$axios.post('/api/api/templetTree/node/getRootNode',{

        }).then((res)=>{
            console.log(res)
            for(var i=0;i<res.data.nodes.length;i++){
                res.data.nodes[i].children=[];
                res.data.nodes[i].num=i;
            }
            this.options=res.data.nodes
            
        }).catch((err)=>{
            console.log(err)
        })
    },
    watch:{
        "value2":function(newVal,oidVal){
            this.bigdatas.fileType=newVal;
            switch (newVal) {
                case 1:
                    this.fileTyepAccept='image/*';
                    this.bigdatas.fileType=1;
                    break;
                case 2:
                    this.fileTyepAccept='audio/*';
                    this.bigdatas.fileType=2;
                    break;
                case 3:
                    this.fileTyepAccept='video/*';
                    this.bigdatas.fileType=3;
                    break;
                case 4:
                    this.fileTyepAccept='application/pdf';
                    this.bigdatas.fileType=4;
                    break;
                case 5:
                    this.fileTyepAccept='*';
                    this.bigdatas.fileType=5;
                    break;
                default:
                    break;
            }

            if(newVal!=""){
                this.$axios.post(
                    '/api/api/archives/data/getFileList',
                    {   
                        filePath:this.bigdatas.filePath,
                        fileType:newVal,
                    }
                ).then(
                    (res)=>{
                        console.log(res)

                        if('errorMsg' in res.data==false){
                            this.dialogTableVisible=true;
                            this.bigdatas.fileList=res.data.fileList;
                        }else{
                            this.operation('error',res.data.errorMsg)
                        }
                        
                    }
                ).catch(
                    (err)=>{
                        console.log(err)
                    }

                )
            
            }else{
                this.dialogTableVisible=false;
            }
        },
        "bigdatas.filePath":function(newVal,oidVal){
            if(newVal!=''){
                for(var i=0;i<this.options2.length;i++){
                    this.options2[i].disabled=false
                }
                
            }else{
                for(var i=0;i<this.options2.length;i++){
                    this.options2[i].disabled=true
                }
            }
        },
    },
    methods:{
        showDetial(index,data){
            this.canShowData=true
            
            console.log('11111111111111',data)
            if(data.fileCount==undefined){
                data.fileCount=0
            }
            
            this.bigData.dataList.loading=true
            this.bigData.dataList.columnsDatas=[]
            this.bigData.dataList.tableDatas=[]
            console.log(index,data)  
            this.$axios.post('/api/api/archives/data/getQueryDetail',{
                tableId:data.tableId,
                DH:data.DH
            }).then((res)=>{
                console.log(res)
                for(var i=0;i<res.data.columns.length;i++){
                    res.data.columns[i].width=res.data.columns[i].columnLength
                    res.data.columns[i].titleAlign='center'
                    res.data.columns[i].columnAlign='center'
                    res.data.columns[i].isResize=true
                    res.data.columns[i].field=res.data.columns[i].abcName
                    res.data.columns[i].title=res.data.columns[i].columnName
                }              
                if(res.data.anJianColumns==undefined){ 
                    this.bigData.dataList.loading=false
                    res.data.columns.unshift(
                        {
                            field: 'fileCount', 
                            title:'文件数量', 
                            width: 15, 
                            titleAlign: 'center',
                            columnAlign:'center',
                            isResize:true
                        }
                    )
                    this.bigData.dataList.columnsDatas=res.data.columns
                    this.bigData.dataList.tableDatas.push(data)
                    this.bigData.dataListShow=true
                }else{
                    console.log('xxxxxxxxxxxxxxx')
                    for(var i=0;i<res.data.anJianColumns.length;i++){
                        res.data.anJianColumns[i].width=res.data.anJianColumns[i].columnLength
                        res.data.anJianColumns[i].titleAlign='center'
                        res.data.anJianColumns[i].columnAlign='center'
                        res.data.anJianColumns[i].isResize=true
                        res.data.anJianColumns[i].field=res.data.anJianColumns[i].abcName
                        res.data.anJianColumns[i].title=res.data.anJianColumns[i].columnName
                    }
                    for(var i=0;i<res.data.anJianData.length;i++){
                        if(res.data.anJianData[i].fileCount==undefined){
                            res.data.anJianData[i].fileCount=0
                        }
                        
                    }
                    this.bigData.dataList.loading=false
                    this.bigData.dataList.columnsDatas=res.data.columns
                    this.bigData.dataList.tableDatas.push(data)
                    res.data.anJianColumns.unshift(
                        {
                            field: 'fileCount', 
                            title:'文件数量', 
                            width: 15, 
                            titleAlign: 'center',
                            columnAlign:'center',
                            isResize:true
                        }
                    )
                    this.bigData.dataList.columnsAjDatas=res.data.anJianColumns
                    this.bigData.dataList.tableAjDatas=res.data.anJianData
                    this.bigData.AjdataListShow=true
                }
            }).catch((err)=>{
                console.log(err)
            })
        },
        operation(status,text){
            var self=this;  
            self.$message({
                type: status,
                message: text
            })
            
            
        },
        rowClick(rowIndex, rowData, column){
            this.canShowData=true
            this.bigdatas.filePath=''
        },
        rowWjClick(rowIndex, rowData, column){
            console.log('1',rowData)
            console.log('2',rowIndex) 
            console.log('3',column)
            if(rowData.fileCount==0){
                this.bigdatas.filePath='';
            }else{
                this.bigdatas.filePath=rowData.filePath;
            }
        },
        handleChange(val) {     
            console.log('active item:', val);
            this.$axios.post('/api/api/templetTree/node/getChildNode',{
                id:val[val.length-1]
            }).then((res)=>{
                console.log("xxxxxxxxxxx",res)
                for(var i=0;i<res.data.nodes.length;i++){
                    res.data.nodes[i].children=[];       
                }
                this.addChild(val,val.length,this.options,res.data.nodes,0)  
                this.bigData.rootNodeId=val[val.length-1];         
            }).catch((err)=>{
                console.log(err)
            })
        },
        handleClick(){
            this.tableData=[];
            if(this.bigData.rootNodeId==''){
                this.operation('warning','请选择搜索范围')
            }else{
                this.$axios.post('/api/api/archives/data/bigQuery',{
                    column:makePy(this.bigData.column)[0],
                    keyword:this.bigData.keyword,
                    rootNodeId:this.bigData.rootNodeId,
                }).then((res)=>{
                    console.log(res)
                    if(res.data.datas.length!=0){

                        res.data.datas.map(item=>{
                            item.value = item[makePy(this.bigData.column)[0]];
                            this.tableData.push(item);
                            })

                    }else{
                        alert('搜索结果为空')
                    }
                }).catch((err)=>{
                    console.log(err)
                })
            }

            // 
            
            
            
        },
        addChild(val,num,options,data,index){
            if(num==1){
                for(var j=0;j<options.length;j++){
                    if(options[j].id==val[index]){
                        options[j].children=data; 
                    }
                }      
            }else{ 
                for(var j=0;j<options.length;j++){
                    
                    if(options[j].id==val[index]){  
                        num--;
                        index++;
                        console.log("111",options[j].children)
                        this.addChild(val,num,options[j].children,data,index)
                    }
                }  
                
            }
              
        },
        
        beforeDialogTableVisible(done){
            this.dialogTableVisible=false;
            this.value2='';
            done();
        },
        showVideoClose(done){
            this.showVideo=false;
            this.videoSrc='';
            done();
        },
        showAudioClose(done){
            this.showAudio=false;
            this.audioSrc='';
            done();
        },
        showPictureClose(done){
            this.showPicture=false;
            this.pictureSrc='';
            done();
        },
        showData(index,val){
            for(var i=0;i<this.bigdatas.fileList.length;i++){
                if(i==index){
                    switch (this.bigdatas.fileType) {
                        case 1:
                            this.picloading=true;
                            this.picName=this.bigdatas.fileList[index].fileName
                            this.showPicture=true
                            this.pictureSrc='/api/api/archives/data/showImage?filePath='+encodeURIComponent(this.bigdatas.fileList[i].filePath)
                            break;
                        case 2:
                            this.showAudio=true
                            this.audioName=this.bigdatas.fileList[i].fileName
                            this.audioSrc='/api/api/archives/data/showAudio?filePath='+encodeURIComponent(this.bigdatas.fileList[i].filePath)
                            break;
                        case 3:
                            this.showVideo=true
                            this.videoName=this.bigdatas.fileList[i].fileName
                            this.videoSrc='/api/api/archives/data/showVideo?filePath='+encodeURIComponent(this.bigdatas.fileList[i].filePath)
                            break;
                        case 4:
                            this.showPdf(this.bigdatas.fileList[i].filePath)
                            break;
                        case 5:
                            this.downloadFile(this.bigdatas.fileList[i].fileName,this.bigdatas.fileList[i].filePath)
                            break;
                        default:
                            break;
                    }
                    
                }
            }
        },
        downloadFile(fileName,filePath){
            var formData = new FormData();
            formData.append('filePath',filePath)
            this.$axios.post(
                '/api/api/archives/data/fileDownload',
                formData,
                {     
                    responseType:'blob',
                    headers:{
                        'Content-Type': 'multipart/form-data'
                    }
                },
                
                
            ).then(
                (res)=>{
                    console.log(res)
                    var blob = new Blob([res.data])
                    var downloadElement = document.createElement('a');
                    var href = window.URL.createObjectURL(blob); //创建下载的链接
                    downloadElement.href = href;
                    downloadElement.download = fileName; //下载后文件名
                    document.body.appendChild(downloadElement);
                    downloadElement.click(); //点击下载
                    document.body.removeChild(downloadElement); //下载完成移除元素
                    window.URL.revokeObjectURL(href); //释放掉blob对象                 
                } 
            ).catch(
                (err)=>{
                    console.log(err)
                } 
            )
            
        },
        showPdf(filePath){
        //创建form表单
            var temp_form = document.createElement("form");
            temp_form.action = "/api/api/archives/data/showPdf";
            //如需打开新窗口，form的target属性要设置为'_blank'
            temp_form.target = "_blank";
            temp_form.method = "post";
            temp_form.style.display = "none";
            var opt = document.createElement("textarea");
            opt.name = "filePath";
            opt.value = filePath
            temp_form.appendChild(opt);
            document.body.appendChild(temp_form);
            //提交数据
            temp_form.submit();
        },
        downloadData(index,val){
            for(var i=0;i<this.bigdatas.fileList.length;i++){
                if(i==index){
                    this.downloadFile(this.bigdatas.fileList[i].fileName,this.bigdatas.fileList[i].filePath)
                    
                }
            }

        },
        lastPic(){
            this.picloading=true;
            console.log('++++++++++++++++++++++++++++++++',this.picIndex)
    
            if(this.picIndex!=0){
                this.showPicture=true
                this.picName=this.bigdatas.fileList[this.picIndex-1].fileName
                this.pictureSrc='/api/api/archives/data/showImage?filePath='+encodeURIComponent(this.bigdatas.fileList[this.picIndex-1].filePath)
                this.picIndex-=1;
                //this.picloading=false
            }else if(this.picIndex==0){
                this.showPicture=true
                this.picName=this.bigdatas.fileList[this.bigdatas.fileList.length-1].fileName
                this.pictureSrc='/api/api/archives/data/showImage?filePath='+encodeURIComponent(this.bigdatas.fileList[this.bigdatas.fileList.length-1].filePath)
                this.picIndex=this.bigdatas.fileList.length-1;
                //this.picloading=false
            }
            
            
        },
        nextPic(){
            this.picloading=true;
            console.log('++++++++++++++++++++++++++++++++',this.picIndex)
            
            if(this.picIndex!=this.bigdatas.fileList.length-1){
                this.showPicture=true
                this.picName=this.bigdatas.fileList[this.picIndex+1].fileName
                this.pictureSrc='/api/api/archives/data/showImage?filePath='+encodeURIComponent(this.bigdatas.fileList[this.picIndex+1].filePath)
                this.picIndex+=1;
                //this.picloading=false;
            }else if(this.picIndex==this.bigdatas.fileList.length-1){
                this.showPicture=true
                this.picName=this.bigdatas.fileList[0].fileName
                this.pictureSrc='/api/api/archives/data/showImage?filePath='+encodeURIComponent(this.bigdatas.fileList[0].filePath)
                this.picIndex=0;
                //this.picloading=false
            }
            

        },
        lastVid(){
            
            console.log('++++++++++++++++++++++++++++++++',this.picIndex)
    
            if(this.picIndex!=0){
                this.showVideo=true
                this.videoName=this.bigdatas.fileList[this.picIndex-1].fileName
                this.videoSrc='/api/api/archives/data/showVideo?filePath='+encodeURIComponent(this.bigdatas.fileList[this.picIndex-1].filePath)
                this.picIndex-=1;
                //this.picloading=false
            }else if(this.picIndex==0){
                this.showVideo=true
                this.videoName=this.bigdatas.fileList[this.bigdatas.fileList.length-1].fileName
                this.videoSrc='/api/api/archives/data/showVideo?filePath='+encodeURIComponent(this.bigdatas.fileList[this.bigdatas.fileList.length-1].filePath)
                this.picIndex=this.bigdatas.fileList.length-1;
                //this.picloading=false
            }
            
            
        },
        nextVid(){
           
            console.log('++++++++++++++++++++++++++++++++',this.picIndex)
            
            if(this.picIndex!=this.bigdatas.fileList.length-1){
                this.showVideo=true
                this.videoName=this.bigdatas.fileList[this.picIndex+1].fileName
                this.videoSrc='/api/api/archives/data/showVideo?filePath='+encodeURIComponent(this.bigdatas.fileList[this.picIndex+1].filePath)
                this.picIndex+=1;
                //this.picloading=false;
            }else if(this.picIndex==this.bigdatas.fileList.length-1){
                this.showVideo=true
                this.videoName=this.bigdatas.fileList[0].fileName
                this.videoSrc='/api/api/archives/data/showVideo?filePath='+encodeURIComponent(this.bigdatas.fileList[0].filePath)
                this.picIndex=0;
                //this.picloading=false
            }
            

        },
        lastAudio(){
            
            console.log('++++++++++++++++++++++++++++++++',this.picIndex)
    
            if(this.picIndex!=0){
                this.showAudio=true
                this.audioName=this.bigdatas.fileList[this.picIndex-1].fileName
                this.audioSrc='/api/api/archives/data/showAudio?filePath='+encodeURIComponent(this.bigdatas.fileList[this.picIndex-1].filePath)
                this.picIndex-=1;
                //this.picloading=false
            }else if(this.picIndex==0){
                this.showAudio=true
                this.audioName=this.bigdatas.fileList[this.bigdatas.fileList.length-1].fileName
                this.audioSrc='/api/api/archives/data/showAudio?filePath='+encodeURIComponent(this.bigdatas.fileList[this.bigdatas.fileList.length-1].filePath)
                this.picIndex=this.bigdatas.fileList.length-1;
                //this.picloading=false
            }
            
            
        },
        nextAudio(){
            
            console.log('++++++++++++++++++++++++++++++++',this.picIndex)
            
            if(this.picIndex!=this.bigdatas.fileList.length-1){
                this.showAudio=true
                this.audioName=this.bigdatas.fileList[this.picIndex+1].fileName
                this.audioSrc='/api/api/archives/data/showAudio?filePath='+encodeURIComponent(this.bigdatas.fileList[this.picIndex+1].filePath)
                this.picIndex+=1;
                //this.picloading=false;
            }else if(this.picIndex==this.bigdatas.fileList.length-1){
                this.showAudio=true
                this.audioName=this.bigdatas.fileList[0].fileName
                this.audioSrc='/api/api/archives/data/showAudio?filePath='+encodeURIComponent(this.bigdatas.fileList[0].filePath)
                this.picIndex=0;
                //this.picloading=false
            }
            

        },
        onloadeddata(){
            console.log('00000000000000000000000000000')
            this.picloading=false
        }
        

    }
}   

</script>

